<a href="https://colab.research.google.com/github/elerufe/DiploDatosFaMAF/blob/main/EyCD/G25_Entregable_EyCD_parte_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Grupo 25 - Entregable EyCD

#Parte 1 de 2

Integrantes:

Rufeil Fiori, Elena

Sosa, Manuel

Taié Mirón, Macarena

Yurovich, Luis Federico

**Diplomatura en Ciencia de Datos, Aprendizaje Automático y sus Aplicaciones**

**Exploración y Curación de Datos**

*Edición 2022*

----

# Trabajo práctico entregable - parte 1

En esta notebook, vamos a cargar el conjunto de datos de [la compentencia Kaggle](https://www.kaggle.com/dansbecker/melbourne-housing-snapshot) sobre estimación de precios de ventas de propiedades en Melbourne, Australia.

Utilizaremos el conjunto de datos reducido producido por [DanB](https://www.kaggle.com/dansbecker). Hemos subido una copia a un servidor de la Universidad Nacional de Córdoba para facilitar su acceso remoto.

In [ ]:
import matplotlib.pyplot as plt
import numpy
import pandas

import seaborn
seaborn.set_context('talk')

!pip install python-decouple
#from decouple import config
from sqlalchemy import create_engine, text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting python-decouple
  Downloading python_decouple-3.6-py3-none-any.whl (9.9 kB)
Installing collected packages: python-decouple
Successfully installed python-decouple-3.6

In [ ]:
import plotly
plotly.__version__
# Make sure it's 4.14.3

'5.5.0'

In [ ]:
melbourne_df = pandas.read_csv(
    'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/melb_data.csv')
melb_df = melbourne_df.copy()
melb_df[:3]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

Primero inspeccionamos las columnas del dataframe

In [ ]:
melb_df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

Aqui observamos la cantidad de registros.

In [ ]:
len(melb_df)

13580

Cargamos la base de datos de airbnb.

In [ ]:
airbnb_df = pandas.read_csv('https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/cleansed_listings_dec18.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (35,77) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
airbnb_df[:3]

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,neighborhood_overview,notes,...,review_scores_location,review_scores_value,requires_license,license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,9835,https://www.airbnb.com/rooms/9835,2.018120e+13,12/7/2018,Beautiful Room & House,NaN,"House: Clean, New, Modern, Quite, Safe. 10Km f...","House: Clean, New, Modern, Quite, Safe. 10Km f...",Very safe! Family oriented. Older age group.,NaN,...,9.0,9.0,f,NaN,f,strict_14_with_grace_period,f,f,1,0.04
1,10803,https://www.airbnb.com/rooms/10803,2.018120e+13,12/7/2018,Room in Cool Deco Apartment in Brunswick,A large air conditioned room with queen spring...,The apartment is Deco/Edwardian in style and h...,A large air conditioned room with queen spring...,This hip area is a crossroads between two grea...,NaN,...,9.0,9.0,f,NaN,t,moderate,t,t,1,1.50
2,12936,https://www.airbnb.com/rooms/12936,2.018120e+13,12/7/2018,St Kilda 1BR APT+BEACHSIDE+VIEWS+PARKING+WIFI+AC,RIGHT IN THE HEART OF ST KILDA! It doesn't get...,FREE WiFi FREE in-building remote controlled g...,RIGHT IN THE HEART OF ST KILDA! It doesn't get...,A stay at our apartment means you can enjoy so...,First floor apartment with both lift and stair...,...,9.0,9.0,f,NaN,f,strict_14_with_grace_period,f,f,17,0.15

In [ ]:
print(airbnb_df.isnull().sum()[:50])
print(airbnb_df.isnull().sum()[50:])

id                            0
listing_url                   0
scrape_id                     0
last_scraped                  0
name                          3
summary                     696
space                      6051
description                 332
neighborhood_overview      8471
notes                     11349
transit                    7952
access                     7727
interaction                8358
house_rules                7863
picture_url                   0
host_id                       0
host_url                      0
host_name                     3
host_since                    3
host_location                26
host_about                 9165
host_response_time         7306
host_response_rate         7306
host_is_superhost             3
host_thumbnail_url            3
host_picture_url              3
host_neighborhood          7968
host_verifications            0
host_has_profile_pic          3
host_identity_verified        3
street                        0
neighborhood               5813
city                          0
suburb                       23
state                        61
zipcode                     142
smart_location                0
country_code                  0
country                       0
latitude                      0
longitude                     0
is_location_exact             0
property_type                 0
room_type                     0
accommodates                  0
bathrooms                    17
bedrooms                      5
beds                         34
bed_type                      0
amenities                     0
dtype: int64
price                                   0
weekly_price                        20371
monthly_price                       21004
security_deposit                     7494
cleaning_fee                         5646
guests_included                         0
extra_people                            0
minimum_nights                          0
maximum_nights                          0
calendar_updated                        0
has_availability                        0
availability_30                         0
availability_60                         0
availability_90                         0
availability_365                        0
calendar_last_scraped                   0
number_of_reviews                       0
first_review                         5242
last_review                          5242
review_scores_rating                 5706
review_scores_accuracy               5720
review_scores_cleanliness            5713
review_scores_checkin                5734
review_scores_communication          5718
review_scores_location               5733
review_scores_value                  5735
requires_license                        0
license                             22874
instant_bookable                        0
cancellation_policy                     0
require_guest_profile_picture           0
require_guest_phone_verification        0
calculated_host_listings_count          0
reviews_per_month                    5242
dtype: int64

In [ ]:
airbnb_df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'neighborhood_overview', 'notes', 'transit',
       'access', 'interaction', 'house_rules', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighborhood',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'street', 'neighborhood', 'city', 'suburb', 'state', 'zipcode',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'price',
       'weekly_price', 'monthly_price', 'security_deposit', 'cleaning_fee',
       'guests_included', 'extra_people', 'minimum_nights', 'maximum_nights',
       'calendar_updated', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'calendar_last_scraped', 'number_of_reviews', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'requires_license', 'license',
       'instant_bookable', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

In [ ]:
len(airbnb_df)

22895

## Ejercicio 1 SQL: 

1. Crear una base de datos en SQLite utilizando la libreria [SQLalchemy](https://stackoverflow.com/questions/2268050/execute-sql-from-file-in-sqlalchemy).
https://docs.sqlalchemy.org/en/14/core/engines.html#sqlite

2. Ingestar los datos provistos en 'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/melb_data.csv' en una tabla y el dataset generado en clase con datos de airbnb y sus precios por codigo postal en otra.

3. Implementar consultas en SQL que respondan con la siguiente información:

    - cantidad de registros totales por ciudad.
    - cantidad de registros totales por barrio y ciudad.

4. Combinar los datasets de ambas tablas ingestadas utilizando el comando JOIN de SQL  para obtener un resultado similar a lo realizado con Pandas en clase.

In [ ]:
#Creamos una base de datos en SQLite
#Agregamos primero la base de datos de Melbourne
engine = create_engine('sqlite:///melb_data.sqlite3', echo=True)
melb_df.to_sql('melb_data', con=engine, if_exists="replace")

2022-07-11 21:00:06,424 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("melb_data")
2022-07-11 21:00:06,428 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-11 21:00:06,436 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("melb_data")
2022-07-11 21:00:06,441 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-11 21:00:06,455 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-11 21:00:06,462 INFO sqlalchemy.engine.Engine
CREATE TABLE melb_data (
	"index" BIGINT,
	"Suburb" TEXT,
	"Address" TEXT,
	"Rooms" BIGINT,
	"Type" TEXT,
	"Price" FLOAT,
	"Method" TEXT,
	"SellerG" TEXT,
	"Date" TEXT,
	"Distance" FLOAT,
	"Postcode" FLOAT,
	"Bedroom2" FLOAT,
	"Bathroom" FLOAT,
	"Car" FLOAT,
	"Landsize" FLOAT,
	"BuildingArea" FLOAT,
	"YearBuilt" FLOAT,
	"CouncilArea" TEXT,
	"Lattitude" FLOAT,
	"Longtitude" FLOAT,
	"Regionname" TEXT,
	"Propertycount" FLOAT
)


2022-07-11 21:00:06,467 INFO sqlalchemy.engine.Engine [no key 0.00569s] ()
2022-07-11 21:00:06,484 INFO sqlalchemy.engine.Engine CREATE INDEX ix_melb_data_index ON melb_data ("index")
2022-07-11 21:00:06,487 INFO sqlalchemy.engine.Engine [no key 0.00335s] ()
2022-07-11 21:00:06,509 INFO sqlalchemy.engine.Engine COMMIT
2022-07-11 21:00:06,568 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-11 21:00:07,523 INFO sqlalchemy.engine.Engine INSERT INTO melb_data ("index", "Suburb", "Address", "Rooms", "Type", "Price", "Method", "SellerG", "Date", "Distance", "Postcode", "Bedroom2", "Bathroom", "Car", "Landsize", "BuildingArea", "YearBuilt", "CouncilArea", "Lattitude", "Longtitude", "Regionname", "Propertycount") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-07-11 21:00:07,530 INFO sqlalchemy.engine.Engine [generated in 0.85968s] ((0, 'Abbotsford', '85 Turner St', 2, 'h', 1480000.0, 'S', 'Biggin', '3/12/2016', 2.5, 3067.0, 2.0, 1.0, 1.0, 202.0, None, None, 'Yarra', -37.7996, 144.9984, 'Northern Metropolitan', 4019.0), (1, 'Abbotsford', '25 Bloomburg St', 2, 'h', 1035000.0, 'S', 'Biggin', '4/02/2016', 2.5, 3067.0, 2.0, 1.0, 0.0, 156.0, 79.0, 1900.0, 'Yarra', -37.8079, 144.9934, 'Northern Metropolitan', 4019.0), (2, 'Abbotsford', '5 Charles St', 3, 'h', 1465000.0, 'SP', 'Biggin', '4/03/2017', 2.5, 3067.0, 3.0, 2.0, 0.0, 134.0, 150.0, 1900.0, 'Yarra', -37.8093, 144.9944, 'Northern Metropolitan', 4019.0), (3, 'Abbotsford', '40 Federation La', 3, 'h', 850000.0, 'PI', 'Biggin', '4/03/2017', 2.5, 3067.0, 3.0, 2.0, 1.0, 94.0, None, None, 'Yarra', -37.7969, 144.9969, 'Northern Metropolitan', 4019.0), (4, 'Abbotsford', '55a Park St', 4, 'h', 1600000.0, 'VB', 'Nelson', '4/06/2016', 2.5, 3067.0, 3.0, 1.0, 2.0, 120.0, 142.0, 2014.0, 'Yarra', -37.8072, 144.9941, 'Northern Metropolitan', 4019.0), (5, 'Abbotsford', '129 Charles St', 2, 'h', 941000.0, 'S', 'Jellis', '7/05/2016', 2.5, 3067.0, 2.0, 1.0, 0.0, 181.0, None, None, 'Yarra', -37.8041, 144.9953, 'Northern Metropolitan', 4019.0), (6, 'Abbotsford', '124 Yarra St', 3, 'h', 1876000.0, 'S', 'Nelson', '7/05/2016', 2.5, 3067.0, 4.0, 2.0, 0.0, 245.0, 210.0, 1910.0, 'Yarra', -37.8024, 144.9993, 'Northern Metropolitan', 4019.0), (7, 'Abbotsford', '98 Charles St', 2, 'h', 1636000.0, 'S', 'Nelson', '8/10/2016', 2.5, 3067.0, 2.0, 1.0, 2.0, 256.0, 107.0, 1890.0, 'Yarra', -37.806, 144.9954, 'Northern Metropolitan', 4019.0)  ... displaying 10 of 13580 total bound parameter sets ...  (13578, 'Williamstown', '96 Verdon St', 4, 'h', 2500000.0, 'PI', 'Sweeney', '26/08/2017', 6.8, 3016.0, 4.0, 1.0, 5.0, 866.0, 157.0, 1920.0, None, -37.85908, 144.89299, 'Western Metropolitan', 6380.0), (13579, 'Yarraville', '6 Agnes St', 4, 'h', 1285000.0, 'SP', 'Village', '26/08/2017', 6.3, 3013.0, 4.0, 1.0, 1.0, 362.0, 112.0, 1920.0, None, -37.81188, 144.88449, 'Western Metropolitan', 6543.0))
2022-07-11 21:00:07,702 INFO sqlalchemy.engine.Engine COMMIT

In [ ]:
#Ahora le agregamos la base de datos de airbnb
airbnb_df.to_sql('airbnb', con=engine, if_exists="replace")

2022-07-11 21:00:08,012 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("airbnb")
2022-07-11 21:00:08,014 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-11 21:00:08,021 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("airbnb")
2022-07-11 21:00:08,026 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-11 21:00:08,051 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-11 21:00:08,071 INFO sqlalchemy.engine.Engine
CREATE TABLE airbnb (
	"index" BIGINT,
	id BIGINT,
	listing_url TEXT,
	scrape_id FLOAT,
	last_scraped TEXT,
	name TEXT,
	summary TEXT,
	space TEXT,
	description TEXT,
	neighborhood_overview TEXT,
	notes TEXT,
	transit TEXT,
	access TEXT,
	interaction TEXT,
	house_rules TEXT,
	picture_url TEXT,
	host_id BIGINT,
	host_url TEXT,
	host_name TEXT,
	host_since TEXT,
	host_location TEXT,
	host_about TEXT,
	host_response_time TEXT,
	host_response_rate TEXT,
	host_is_superhost TEXT,
	host_thumbnail_url TEXT,
	host_picture_url TEXT,
	host_neighborhood TEXT,
	host_verifications TEXT,
	host_has_profile_pic TEXT,
	host_identity_verified TEXT,
	street TEXT,
	neighborhood TEXT,
	city TEXT,
	suburb TEXT,
	state TEXT,
	zipcode TEXT,
	smart_location TEXT,
	country_code TEXT,
	country TEXT,
	latitude FLOAT,
	longitude FLOAT,
	is_location_exact TEXT,
	property_type TEXT,
	room_type TEXT,
	accommodates BIGINT,
	bathrooms FLOAT,
	bedrooms FLOAT,
	beds FLOAT,
	bed_type TEXT,
	amenities TEXT,
	price BIGINT,
	weekly_price FLOAT,
	monthly_price FLOAT,
	security_deposit FLOAT,
	cleaning_fee FLOAT,
	guests_included BIGINT,
	extra_people BIGINT,
	minimum_nights BIGINT,
	maximum_nights BIGINT,
	calendar_updated TEXT,
	has_availability TEXT,
	availability_30 BIGINT,
	availability_60 BIGINT,
	availability_90 BIGINT,
	availability_365 BIGINT,
	calendar_last_scraped TEXT,
	number_of_reviews BIGINT,
	first_review TEXT,
	last_review TEXT,
	review_scores_rating FLOAT,
	review_scores_accuracy FLOAT,
	review_scores_cleanliness FLOAT,
	review_scores_checkin FLOAT,
	review_scores_communication FLOAT,
	review_scores_location FLOAT,
	review_scores_value FLOAT,
	requires_license TEXT,
	license TEXT,
	instant_bookable TEXT,
	cancellation_policy TEXT,
	require_guest_profile_picture TEXT,
	require_guest_phone_verification TEXT,
	calculated_host_listings_count BIGINT,
	reviews_per_month FLOAT
)


2022-07-11 21:00:08,074 INFO sqlalchemy.engine.Engine [no key 0.00354s] ()
2022-07-11 21:00:08,098 INFO sqlalchemy.engine.Engine CREATE INDEX ix_airbnb_index ON airbnb ("index")
2022-07-11 21:00:08,100 INFO sqlalchemy.engine.Engine [no key 0.00283s] ()
2022-07-11 21:00:08,117 INFO sqlalchemy.engine.Engine COMMIT
2022-07-11 21:00:08,525 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-11 21:00:16,750 INFO sqlalchemy.engine.Engine INSERT INTO airbnb ("index", id, listing_url, scrape_id, last_scraped, name, summary, space, description, neighborhood_overview, notes, transit, access, interaction, house_rules, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_response_rate, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighborhood, host_verifications, host_has_profile_pic, host_identity_verified, street, neighborhood, city, suburb, state, zipcode, smart_location, country_code, country, latitude, longitude, is_location_exact, property_type, room_type, accommodates, bathrooms, bedrooms, beds, bed_type, amenities, price, weekly_price, monthly_price, security_deposit, cleaning_fee, guests_included, extra_people, minimum_nights, maximum_nights, calendar_updated, has_availability, availability_30, availability_60, availability_90, availability_365, calendar_last_scraped, number_of_reviews, first_review, last_review, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, requires_license, license, instant_bookable, cancellation_policy, require_guest_profile_picture, require_guest_phone_verification, calculated_host_listings_count, reviews_per_month) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

Implementamos consultas en SQL que respondan a la siguiente información: **cantidad de registros totales por ciudad.**

Identificamos las ciudades registradas en el dataset de airbnb.

In [ ]:
airbnb_df["city"].unique()

array(['Manningham', 'Moreland', 'Port Phillip', 'Darebin', 'Casey',
       'Melbourne', 'Monash', 'Frankston', 'Yarra', 'Bayside',
       'Boroondara', 'Kingston', 'Stonnington', 'Glen Eira', 'Maroondah',
       'Maribyrnong', 'Yarra Ranges', 'Banyule', 'Whitehorse', 'Melton',
       'Brimbank', 'Hobsons Bay', 'Wyndham', 'Moonee Valley',
       'Whittlesea', 'Greater Dandenong', 'Nillumbik', 'Knox', 'Cardinia',
       'Hume'], dtype=object)

Aplicamos la herramienta SQL para observar la cantidad de registros totales por ciudad en el dataset de airbnb

In [ ]:
# cantidad de registros por ciudad de la base de datos de airbnb
query1 = """SELECT city, COUNT(city) FROM  airbnb 
GROUP BY city
ORDER BY COUNT(city) DESC """

In [ ]:
with engine.connect() as con:
      rs = con.execute(query1)
      print(query1)
      for row in rs:
          print(row)

2022-07-11 21:00:19,980 INFO sqlalchemy.engine.Engine SELECT city, COUNT(city) FROM  airbnb
GROUP BY city
ORDER BY COUNT(city) DESC
2022-07-11 21:00:19,985 INFO sqlalchemy.engine.Engine [raw sql] ()
SELECT city, COUNT(city) FROM  airbnb
GROUP BY city
ORDER BY COUNT(city) DESC
('Melbourne', 7368)
('Port Phillip', 2808)
('Yarra', 2049)
('Stonnington', 1621)
('Moreland', 967)
('Yarra Ranges', 771)
('Darebin', 698)
('Boroondara', 664)
('Glen Eira', 631)
('Whitehorse', 614)
('Monash', 571)
('Maribyrnong', 436)
('Wyndham', 426)
('Bayside', 375)
('Moonee Valley', 344)
('Manningham', 313)
('Kingston', 309)
('Hobsons Bay', 239)
('Banyule', 203)
('Frankston', 177)
('Knox', 175)
('Hume', 170)
('Casey', 153)
('Greater Dandenong', 147)
('Whittlesea', 137)
('Cardinia', 123)
('Maroondah', 115)
('Brimbank', 108)
('Melton', 95)
('Nillumbik', 88)

Podemos observar una mayor cantidad de registros de la ciudad de Melbourne (7368), con respecto a las demas ciudades.

A continuación, observamos el registro de ciudades correspondiente al dataset melb_df.

In [ ]:
melb_df["CouncilArea"].unique()

array(['Yarra', 'Moonee Valley', 'Port Phillip', 'Darebin', 'Hobsons Bay',
       'Stonnington', 'Boroondara', 'Monash', 'Glen Eira', 'Whitehorse',
       'Maribyrnong', 'Bayside', 'Moreland', 'Manningham', 'Banyule',
       'Melbourne', 'Kingston', 'Brimbank', 'Hume', nan, 'Knox',
       'Maroondah', 'Casey', 'Melton', 'Greater Dandenong', 'Nillumbik',
       'Whittlesea', 'Frankston', 'Macedon Ranges', 'Yarra Ranges',
       'Wyndham', 'Cardinia', 'Unavailable', 'Moorabool'], dtype=object)

Aplicando nuevamente la herramienta SQL, en este caso para el dataset de melb_data.

In [ ]:
# cantidad de registros por ciudad de la base de datos de melb_data
query2 = """SELECT CouncilArea, COUNT(CouncilArea) FROM  melb_data 
GROUP BY CouncilArea
ORDER BY COUNT(CouncilArea) DESC """

In [ ]:
with engine.connect() as con:
      rs = con.execute(query2)
      print(query2)
      for row in rs:
          print(row)

2022-07-11 21:00:20,108 INFO sqlalchemy.engine.Engine SELECT CouncilArea, COUNT(CouncilArea) FROM  melb_data
GROUP BY CouncilArea
ORDER BY COUNT(CouncilArea) DESC
2022-07-11 21:00:20,112 INFO sqlalchemy.engine.Engine [raw sql] ()
SELECT CouncilArea, COUNT(CouncilArea) FROM  melb_data
GROUP BY CouncilArea
ORDER BY COUNT(CouncilArea) DESC
('Moreland', 1163)
('Boroondara', 1160)
('Moonee Valley', 997)
('Darebin', 934)
('Glen Eira', 848)
('Stonnington', 719)
('Maribyrnong', 692)
('Yarra', 647)
('Port Phillip', 628)
('Banyule', 594)
('Bayside', 489)
('Melbourne', 470)
('Hobsons Bay', 434)
('Brimbank', 424)
('Monash', 333)
('Manningham', 311)
('Whitehorse', 304)
('Kingston', 207)
('Whittlesea', 167)
('Hume', 164)
('Wyndham', 86)
('Knox', 80)
('Maroondah', 80)
('Melton', 66)
('Frankston', 53)
('Greater Dandenong', 52)
('Casey', 38)
('Nillumbik', 36)
('Yarra Ranges', 18)
('Cardinia', 8)
('Macedon Ranges', 7)
('Moorabool', 1)
('Unavailable', 1)
(None, 0)

Comparando los resultados obtenidos para ambos conjunto de datos, podemos decir que:


*   Existe una clara diferencia de registros de la ciudad de Melbourne en ambos datasets, observando que la cantidad de registros de esta ciudad en el conjunto de datos de airbnb es de 7368, mientras que en el dataset de melb_df, dicha cantidad es mucho menor (470 registros). Lo mismo ocurre en menor medida para las ciudadades de: Port Phillip, Yarra y Stonnington. 
*   Ademas, se puede observar que hay una mayor cantidad de registros totales en el conjunto de datos de airbnb.

Implementamos consultas en SQL que respondan a la siguiente información:
**cantidad de registros totales por barrio y ciudad.**

In [ ]:
airbnb_df["neighborhood"].unique()

array(['Balwyn North', 'Brunswick', 'St Kilda', 'Thornbury',
       'St Kilda East', nan, 'Richmond', 'Central Business District',
       'Brighton', 'Kew', 'Fitzroy', 'Clifton Hill', 'Northcote',
       'Port Melbourne', 'South Melbourne', 'Windsor', 'Parkville',
       'South Yarra', 'Yarraville/Seddon', 'Elwood', 'Middle Park',
       'Hawthorn', 'Carlton', 'Caulfield', 'Coburg', 'North Melbourne',
       'Prahran', 'East Melbourne', 'Albert Park', 'Collingwood',
       'Abbotsford', 'Spotswood/South Kingsville', 'Armadale',
       'Southbank', 'Balwyn', 'Balaclava/Ripponlea', 'Toorak',
       'Malvern East', 'Flemington', 'Prahran/Windsor', 'Footscray',
       'Preston', 'Carnegie', 'Ashburton', 'Fitzroy North', 'Alphington',
       'Docklands', 'Glen Iris', 'Ormond/McKinnon', 'South Wharf',
       'Bentleigh', 'Newport', 'Carlton North', 'West Melbourne',
       'Kensington', 'Williamstown', 'Camberwell', 'Burnley', 'Malvern',
       'Canterbury'], dtype=object)

In [ ]:
#Cantidad de registros totales por ciudad y barrio de la base de datos airbnb
query3 = """SELECT city, neighborhood, COUNT(neighborhood) 
FROM  airbnb
GROUP BY city, neighborhood"""

In [ ]:
with engine.connect() as con:
      rs = con.execute(query3)
      print(query3)
      for row in rs:
          print(row)

2022-07-11 21:00:20,210 INFO sqlalchemy.engine.Engine SELECT city, neighborhood, COUNT(neighborhood)
FROM  airbnb
GROUP BY city, neighborhood
2022-07-11 21:00:20,218 INFO sqlalchemy.engine.Engine [raw sql] ()
SELECT city, neighborhood, COUNT(neighborhood)
FROM  airbnb
GROUP BY city, neighborhood
('Banyule', None, 0)
('Banyule', 'Alphington', 16)
('Banyule', 'Preston', 8)
('Banyule', 'Thornbury', 5)
('Bayside', None, 0)
('Bayside', 'Bentleigh', 1)
('Bayside', 'Brighton', 203)
('Bayside', 'Elwood', 1)
('Boroondara', None, 0)
('Boroondara', 'Ashburton', 14)
('Boroondara', 'Balwyn', 70)
('Boroondara', 'Balwyn North', 40)
('Boroondara', 'Camberwell', 82)
('Boroondara', 'Canterbury', 24)
('Boroondara', 'Glen Iris', 32)
('Boroondara', 'Hawthorn', 261)
('Boroondara', 'Kew', 109)
('Boroondara', 'Malvern', 2)
('Brimbank', None, 0)
('Cardinia', None, 0)
('Casey', None, 0)
('Darebin', None, 0)
('Darebin', 'Alphington', 22)
('Darebin', 'Coburg', 4)
('Darebin', 'Northcote', 303)
('Darebin', 'Preston', 156)
('Darebin', 'Thornbury', 101)
('Frankston', None, 0)
('Glen Eira', None, 0)
('Glen Eira', 'Balaclava/Ripponlea', 2)
('Glen Eira', 'Bentleigh', 84)
('Glen Eira', 'Brighton', 2)
('Glen Eira', 'Carnegie', 126)
('Glen Eira', 'Caulfield', 299)
('Glen Eira', 'Ormond/McKinnon', 46)
('Glen Eira', 'St Kilda East', 39)
('Greater Dandenong', None, 0)
('Hobsons Bay', None, 0)
('Hobsons Bay', 'Newport', 45)
('Hobsons Bay', 'Spotswood/South Kingsville', 23)
('Hobsons Bay', 'Williamstown', 75)
('Hobsons Bay', 'Yarraville/Seddon', 6)
('Hume', None, 0)
('Kingston', None, 0)
('Kingston', 'Bentleigh', 17)
('Knox', None, 0)
('Manningham', None, 0)
('Manningham', 'Balwyn North', 17)
('Maribyrnong', None, 0)
('Maribyrnong', 'Footscray', 253)
('Maribyrnong', 'Yarraville/Seddon', 126)
('Maroondah', None, 0)
('Melbourne', None, 0)
('Melbourne', 'Brunswick', 7)
('Melbourne', 'Carlton', 582)
('Melbourne', 'Carlton North', 10)
('Melbourne', 'Central Business District', 3726)
('Melbourne', 'Docklands', 576)
('Melbourne', 'East Melbourne', 180)
('Melbourne', 'Flemington', 12)
('Melbourne', 'Kensington', 107)
('Melbourne', 'North Melbourne', 290)
('Melbourne', 'Parkville', 85)
('Melbourne', 'Port Melbourne', 8)
('Melbourne', 'Prahran/Windsor', 35)
('Melbourne', 'South Melbourne', 1)
('Melbourne', 'South Wharf', 24)
('Melbourne', 'South Yarra', 161)
('Melbourne', 'Southbank', 1204)
('Melbourne', 'West Melbourne', 119)
('Melton', None, 0)
('Monash', None, 0)
('Monash', 'Ashburton', 4)
('Monash', 'Bentleigh', 5)
('Monash', 'Carnegie', 24)
('Monash', 'Glen Iris', 5)
('Monash', 'Malvern East', 17)
('Moonee Valley', None, 0)
('Moonee Valley', 'Brunswick', 33)
('Moonee Valley', 'Flemington', 166)
('Moonee Valley', 'Kensington', 1)
('Moreland', None, 0)
('Moreland', 'Brunswick', 681)
('Moreland', 'Coburg', 144)
('Moreland', 'Fitzroy North', 6)
('Nillumbik', None, 0)
('Port Phillip', None, 0)
('Port Phillip', 'Albert Park', 74)
('Port Phillip', 'Balaclava/Ripponlea', 141)
('Port Phillip', 'Elwood', 308)
('Port Phillip', 'Middle Park', 50)
('Port Phillip', 'Port Melbourne', 243)
('Port Phillip', 'Prahran/Windsor', 156)
('Port Phillip', 'South Melbourne', 291)
('Port Phillip', 'South Yarra', 133)
('Port Phillip', 'Southbank', 44)
('Port Phillip', 'St Kilda', 1082)
('Port Phillip', 'St Kilda East', 159)
('Port Phillip', 'Windsor', 2)
('Stonnington', None, 0)
('Stonnington', 'Armadale', 71)
('Stonnington', 'Caulfield', 3)
('Stonnington', 'Glen Iris', 44)
('Stonnington', 'Malvern', 34)
('Stonnington', 'Malvern East', 100)
('Stonnington', 'Prahran', 257)
('Stonnington', 'Prahran/Windsor', 4)
('Stonnington', 'South Yarra', 759)
('Stonnington', 'St Kilda', 3)
('Stonnington', 'St Kilda East', 2)
('Stonnington', 'Toorak', 117)
('Stonnington', 'Windsor', 165)
('Whitehorse', None, 0)
('Whitehorse', 'Balwyn', 25)
('Whitehorse', 'Balwyn North', 4)
('Whitehorse', 'Camberwell', 10)
('Whitehorse', 'Glen Iris', 1)
('Whittlesea', None, 0)
('Wyndham', None, 0)
('Yarra', None, 0)
('Yarra', 'Abbotsford', 254)
('Yarra', 'Alphington', 16)
('Yarra', 'Brunswick', 7)
('Yarra', 'Burnley', 56)
('Yarra', 'Carlton', 3)
('Yarra', 'Carlton North', 128)
('Yarra', 'Clifton Hill', 59)
('Yarra', 'Collingwood', 283)
('Yarra', 'East Melbourne', 8)
('Yarra', 'Fitzroy', 381)
('Yarra', 'Fitzroy North', 225)
('Yarra', 'Northcote', 6)
('Yarra', 'Richmond', 547)
('Yarra Ranges', None, 0)

In [ ]:
melb_df["Suburb"].unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Kooyong', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'Melbourne', 'Middle Park', 'Mont Albert',
       'Moonee Ponds', 'Moorabbin', 'Newport', 'Niddrie',
       'North Melbourne', 'Northcote', 'Oak Park', 'Oakleigh South',
       'Parkville', 'Pascoe Vale', 'Port Melbourne', 'Prahran', 'Preston',
       'Reservoir', 'Richmond', 'Rosanna', 'Seddon', 'South Melbourne',
       'South Yarra', 'Southbank', 'Spotswood', 'St Kilda', 'Strathmore',
       'Sunshine', 'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Campbellfield', 'Carlton',
       'East Melbourne', 'Essendon West', 'Fawkner', 'Hawthorn East',
       'Heidelberg', 'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville',
       'Murrumbeena', 'Ormond', 'West Footscray', 'Albion', 'Brooklyn',
       'Glen Huntly', 'Oakleigh', 'Ripponlea', 'Cremorne', 'Docklands',
       'South Kingsville', 'Strathmore Heights', 'Travancore',
       'Caulfield East', 'Seaholme', 'Keilor Park', 'Gardenvale',
       'Princes Hill', 'Bayswater', 'Bayswater North', 'Beaumaris',
       'Berwick', 'Boronia', 'Briar Hill', 'Broadmeadows', 'Bundoora',
       'Burnside Heights', 'Burwood East', 'Cairnlea', 'Caroline Springs',
       'Cheltenham', 'Craigieburn', 'Cranbourne', 'Croydon', 'Dandenong',
       'Dandenong North', 'Diamond Creek', 'Dingley Village',
       'Doncaster East', 'Donvale', 'Doreen', 'Eltham', 'Epping',
       'Forest Hill', 'Frankston', 'Frankston North', 'Frankston South',
       'Gisborne', 'Gladstone Park', 'Greensborough', 'Hallam',
       'Healesville', 'Highett', 'Hillside', 'Huntingdale',
       'Keilor Downs', 'Keilor Lodge', 'Keysborough', 'Kings Park',
       'Lalor', 'Lower Plenty', 'Melton', 'Mernda', 'Mill Park',
       'Mitcham', 'Montmorency', 'Mordialloc', 'Mount Waverley',
       'Narre Warren', 'Nunawading', 'Oakleigh East', 'Parkdale',
       'Point Cook', 'Ringwood East', 'Rockbank', 'Rowville',
       'Sandringham', 'Seaford', 'Skye', 'South Morang', 'Springvale',
       'St Albans', 'Sunbury', 'Tarneit', 'Taylors Hill', 'Taylors Lakes',
       'The Basin', 'Thomastown', 'Truganina', 'Tullamarine', 'Vermont',
       'Wantirna', 'Wantirna South', 'Werribee', 'Westmeadows',
       'Williams Landing', 'Wollert', 'Wyndham Vale', 'Black Rock',
       'Blackburn', 'Blackburn North', 'Bonbeach', 'Carrum', 'Chelsea',
       'Clayton', 'Doveton', 'Ferntree Gully', 'Glen Waverley',
       'Greenvale', 'Heathmont', 'Hoppers Crossing', 'McKinnon',
       'Melton South', 'Melton West', 'Mentone', 'Mooroolbark',
       'Mulgrave', 'Ringwood', 'Roxburgh Park', 'Seabrook', 'Templestowe',
       'Vermont South', 'Warrandyte', 'Watsonia North', 'Wheelers Hill',
       'Altona Meadows', 'Blackburn South', 'Carrum Downs',
       'Clayton South', 'Croydon North', 'Langwarrin', 'Noble Park',
       'Notting Hill', 'Ringwood North', 'Sydenham', 'Albanvale',
       'Beaconsfield Upper', 'Chelsea Heights', 'Dallas', 'Deer Park',
       'Eltham North', 'Keilor', 'Meadow Heights', 'Mount Evelyn',
       'North Warrandyte', 'Pakenham', 'Riddells Creek', 'Sandhurst',
       'Scoresby', 'Silvan', 'Aspendale', 'Chirnside Park',
       'Croydon Hills', 'Croydon South', 'Derrimut', 'Diggers Rest',
       'Edithvale', 'Hampton Park', 'Knoxfield', 'St Helena', 'Upwey',
       'Bacchus Marsh', 'Coolaroo', 'Cranbourne North', 'Kilsyth',
       'Montrose', 'Aspendale Gardens', 'Bullengarook', 'Clarinda',
       'Deepdene', 'Delahey', 'Hurstbridge', 'Kurunjang', 'Wonga Park',
       'Endeavour Hills', 'Officer', 'Waterways', 'Ardeer',
       'Beaconsfield', 'Springvale South', 'Yarra Glen', 'Brookfield',
       'Emerald', 'Whittlesea', 'Burnside', 'Attwood', 'Wallan',
       'New Gisborne', 'Plumpton', 'Monbulk'], dtype=object)

In [ ]:
#Cantidad de registros totales por ciudad y barrio de la base de datos melb_data
query4 = """SELECT CouncilArea, Suburb, COUNT(Suburb) 
FROM  melb_data
GROUP BY CouncilArea, Suburb"""

In [ ]:
with engine.connect() as con:
      rs = con.execute(query4)
      print(query4)
      for row in rs:
          print(row)

2022-07-11 21:00:20,443 INFO sqlalchemy.engine.Engine SELECT CouncilArea, Suburb, COUNT(Suburb)
FROM  melb_data
GROUP BY CouncilArea, Suburb
2022-07-11 21:00:20,446 INFO sqlalchemy.engine.Engine [raw sql] ()
SELECT CouncilArea, Suburb, COUNT(Suburb)
FROM  melb_data
GROUP BY CouncilArea, Suburb
(None, 'Abbotsford', 1)
(None, 'Aberfeldie', 4)
(None, 'Airport West', 6)
(None, 'Albanvale', 2)
(None, 'Albert Park', 5)
(None, 'Albion', 3)
(None, 'Alphington', 2)
(None, 'Altona', 5)
(None, 'Altona Meadows', 2)
(None, 'Altona North', 7)
(None, 'Ardeer', 1)
(None, 'Armadale', 9)
(None, 'Ascot Vale', 5)
(None, 'Ashburton', 7)
(None, 'Ashwood', 1)
(None, 'Aspendale', 3)
(None, 'Aspendale Gardens', 2)
(None, 'Attwood', 1)
(None, 'Avondale Heights', 1)
(None, 'Balaclava', 2)
(None, 'Balwyn', 6)
(None, 'Balwyn North', 20)
(None, 'Bayswater', 2)
(None, 'Bayswater North', 3)
(None, 'Beaumaris', 7)
(None, 'Bellfield', 1)
(None, 'Bentleigh', 8)
(None, 'Bentleigh East', 15)
(None, 'Berwick', 2)
(None, 'Black Rock', 4)
(None, 'Blackburn', 8)
(None, 'Blackburn North', 7)
(None, 'Blackburn South', 4)
(None, 'Bonbeach', 3)
(None, 'Boronia', 2)
(None, 'Box Hill', 5)
(None, 'Braybrook', 2)
(None, 'Briar Hill', 3)
(None, 'Brighton', 10)
(None, 'Brighton East', 10)
(None, 'Broadmeadows', 6)
(None, 'Brooklyn', 1)
(None, 'Brunswick', 14)
(None, 'Brunswick East', 8)
(None, 'Brunswick West', 8)
(None, 'Bulleen', 6)
(None, 'Bundoora', 11)
(None, 'Burnside', 2)
(None, 'Burnside Heights', 1)
(None, 'Burwood', 9)
(None, 'Burwood East', 4)
(None, 'Camberwell', 8)
(None, 'Campbellfield', 1)
(None, 'Canterbury', 3)
(None, 'Carlton', 3)
(None, 'Carlton North', 4)
(None, 'Carnegie', 8)
(None, 'Caroline Springs', 2)
(None, 'Carrum Downs', 5)
(None, 'Caulfield East', 1)
(None, 'Caulfield South', 2)
(None, 'Chadstone', 1)
(None, 'Chelsea', 1)
(None, 'Chelsea Heights', 2)
(None, 'Cheltenham', 16)
(None, 'Clarinda', 2)
(None, 'Clayton', 2)
(None, 'Clayton South', 8)
(None, 'Clifton Hill', 5)
(None, 'Coburg', 14)
(None, 'Coburg North', 2)
(None, 'Collingwood', 3)
(None, 'Coolaroo', 2)
(None, 'Craigieburn', 16)
(None, 'Cranbourne', 1)
(None, 'Cremorne', 1)
(None, 'Croydon', 8)
(None, 'Croydon Hills', 2)
(None, 'Croydon North', 1)
(None, 'Dallas', 2)
(None, 'Dandenong', 2)
(None, 'Dandenong North', 3)
(None, 'Deer Park', 4)
(None, 'Delahey', 2)
(None, 'Derrimut', 2)
(None, 'Diamond Creek', 3)
(None, 'Dingley Village', 5)
(None, 'Doncaster', 8)
(None, 'Doncaster East', 14)
(None, 'Donvale', 5)
(None, 'Doreen', 3)
(None, 'Doveton', 2)
(None, 'Eaglemont', 1)
(None, 'Edithvale', 4)
(None, 'Elsternwick', 2)
(None, 'Eltham', 6)
(None, 'Eltham North', 4)
(None, 'Elwood', 5)
(None, 'Epping', 14)
(None, 'Essendon', 12)
(None, 'Essendon North', 2)
(None, 'Fairfield', 4)
(None, 'Fawkner', 5)
(None, 'Ferntree Gully', 8)
(None, 'Fitzroy', 6)
(None, 'Fitzroy North', 6)
(None, 'Flemington', 7)
(None, 'Footscray', 6)
(None, 'Forest Hill', 8)
(None, 'Frankston', 8)
(None, 'Frankston North', 1)
(None, 'Frankston South', 9)
(None, 'Gisborne', 3)
(None, 'Gladstone Park', 8)
(None, 'Glen Huntly', 1)
(None, 'Glen Iris', 23)
(None, 'Glen Waverley', 19)
(None, 'Glenroy', 15)
(None, 'Gowanbrae', 3)
(None, 'Greensborough', 10)
(None, 'Greenvale', 2)
(None, 'Hadfield', 1)
(None, 'Hallam', 1)
(None, 'Hampton', 14)
(None, 'Hampton East', 5)
(None, 'Hampton Park', 1)
(None, 'Hawthorn', 5)
(None, 'Hawthorn East', 4)
(None, 'Heathmont', 5)
(None, 'Heidelberg', 1)
(None, 'Heidelberg Heights', 2)
(None, 'Heidelberg West', 2)
(None, 'Highett', 7)
(None, 'Hillside', 5)
(None, 'Hoppers Crossing', 15)
(None, 'Huntingdale', 3)
(None, 'Hurstbridge', 1)
(None, 'Ivanhoe', 1)
(None, 'Ivanhoe East', 2)
(None, 'Jacana', 3)
(None, 'Kealba', 2)
(None, 'Keilor', 4)
(None, 'Keilor Downs', 4)
(None, 'Keilor East', 19)
(None, 'Keilor Lodge', 1)
(None, 'Keilor Park', 1)
(None, 'Kensington', 1)
(None, 'Kew', 20)
(None, 'Kew East', 11)
(None, 'Keysborough', 2)
(None, 'Kilsyth', 3)
(None, 'Kings Park', 1)
(None, 'Kingsville', 4)
(None, 'Kooyong', 1)
(None, 'Lalor', 14)
(None, 'Langwarrin', 1)
(None, 'Maidstone', 4)
(None, 'Malvern', 5)
(None, 'Malvern East', 6)
(None, 'Maribyrnong', 4)
(None, 'McKinnon', 3)
(None, 'Meadow Heights', 6)
(None, 'Melton', 4)
(None, 'Melton South', 3)
(None, 'Melton West', 3)
(None, 'Mentone', 10)
(None, 'Mernda', 3)
(None, 'Middle Park', 3)
(None, 'Mill Park', 10)
(None, 'Mitcham', 11)
(None, 'Monbulk', 1)
(None, 'Mont Albert', 3)
(None, 'Montmorency', 2)
(None, 'Moonee Ponds', 10)
(None, 'Moorabbin', 4)
(None, 'Mooroolbark', 3)
(None, 'Mordialloc', 3)
(None, 'Mount Evelyn', 1)
(None, 'Mount Waverley', 13)
(None, 'Mulgrave', 11)
(None, 'Murrumbeena', 2)
(None, 'Narre Warren', 1)
(None, 'New Gisborne', 1)
(None, 'Newport', 8)
(None, 'Niddrie', 9)
(None, 'North Melbourne', 5)
(None, 'North Warrandyte', 1)
(None, 'Northcote', 13)
(None, 'Notting Hill', 1)
(None, 'Nunawading', 2)
(None, 'Oak Park', 5)
(None, 'Oakleigh', 4)
(None, 'Oakleigh East', 1)
(None, 'Oakleigh South', 6)
(None, 'Ormond', 9)
(None, 'Parkdale', 7)
(None, 'Pascoe Vale', 10)
(None, 'Plumpton', 1)
(None, 'Point Cook', 4)
(None, 'Port Melbourne', 13)
(None, 'Prahran', 10)
(None, 'Preston', 10)
(None, 'Princes Hill', 1)
(None, 'Reservoir', 36)
(None, 'Richmond', 9)
(None, 'Ringwood', 7)
(None, 'Ringwood East', 3)
(None, 'Ringwood North', 3)
(None, 'Rosanna', 7)
(None, 'Roxburgh Park', 8)
(None, 'Sandringham', 8)
(None, 'Scoresby', 3)
(None, 'Seaford', 2)
(None, 'Seddon', 2)
(None, 'South Melbourne', 9)
(None, 'South Morang', 3)
(None, 'South Yarra', 5)
(None, 'Spotswood', 2)
(None, 'Springvale', 3)
(None, 'Springvale South', 2)
(None, 'St Albans', 5)
(None, 'St Helena', 1)
(None, 'St Kilda', 2)
(None, 'Strathmore', 5)
(None, 'Strathmore Heights', 1)
(None, 'Sunbury', 21)
(None, 'Sunshine', 2)
(None, 'Sunshine North', 8)
(None, 'Sunshine West', 5)
(None, 'Surrey Hills', 11)
(None, 'Tarneit', 1)
(None, 'Taylors Lakes', 4)
(None, 'Templestowe', 4)
(None, 'Templestowe Lower', 8)
(None, 'The Basin', 1)
(None, 'Thomastown', 5)
(None, 'Thornbury', 7)
(None, 'Toorak', 1)
(None, 'Truganina', 1)
(None, 'Tullamarine', 2)
(None, 'Vermont', 4)
(None, 'Vermont South', 5)
(None, 'Viewbank', 3)
(None, 'Wallan', 1)
(None, 'Wantirna', 5)
(None, 'Wantirna South', 9)
(None, 'Warrandyte', 2)
(None, 'Waterways', 1)
(None, 'Watsonia', 3)
(None, 'Watsonia North', 1)
(None, 'Werribee', 13)
(None, 'West Footscray', 9)
(None, 'West Melbourne', 2)
(None, 'Westmeadows', 3)
(None, 'Wheelers Hill', 13)
(None, 'Williams Landing', 1)
(None, 'Williamstown', 7)
(None, 'Williamstown North', 1)
(None, 'Windsor', 5)
(None, 'Wollert', 3)
(None, 'Wyndham Vale', 1)
(None, 'Yallambie', 1)
(None, 'Yarraville', 10)
('Banyule', 'Bellfield', 15)
('Banyule', 'Briar Hill', 5)
('Banyule', 'Bundoora', 13)
('Banyule', 'Eaglemont', 22)
('Banyule', 'Eltham North', 2)
('Banyule', 'Greensborough', 21)
('Banyule', 'Heidelberg', 50)
('Banyule', 'Heidelberg Heights', 76)
('Banyule', 'Heidelberg West', 74)
('Banyule', 'Ivanhoe', 97)
('Banyule', 'Ivanhoe East', 23)
('Banyule', 'Lower Plenty', 5)
('Banyule', 'Montmorency', 15)
('Banyule', 'Preston', 1)
('Banyule', 'Rosanna', 54)
('Banyule', 'St Helena', 2)
('Banyule', 'Viewbank', 38)
('Banyule', 'Watsonia', 49)
('Banyule', 'Watsonia North', 9)
('Banyule', 'Yallambie', 23)
('Bayside', 'Beaumaris', 11)
('Bayside', 'Black Rock', 8)
('Bayside', 'Brighton', 176)
('Bayside', 'Brighton East', 124)
('Bayside', 'Cheltenham', 4)
('Bayside', 'Hampton', 115)
('Bayside', 'Hampton East', 18)
('Bayside', 'Highett', 16)
('Bayside', 'Sandringham', 17)
('Boroondara', 'Ashburton', 53)
('Boroondara', 'Balwyn', 101)
('Boroondara', 'Balwyn North', 151)
('Boroondara', 'Camberwell', 124)
('Boroondara', 'Canterbury', 51)
('Boroondara', 'Deepdene', 2)
('Boroondara', 'Glen Iris', 117)
('Boroondara', 'Hawthorn', 186)
('Boroondara', 'Hawthorn East', 115)
('Boroondara', 'Kew', 157)
('Boroondara', 'Kew East', 38)
('Boroondara', 'Mont Albert', 1)
('Boroondara', 'Surrey Hills', 64)
('Brimbank', 'Albanvale', 4)
('Brimbank', 'Albion', 38)
('Brimbank', 'Ardeer', 2)
('Brimbank', 'Brooklyn', 1)
('Brimbank', 'Cairnlea', 7)
('Brimbank', 'Deer Park', 10)
('Brimbank', 'Delahey', 4)
('Brimbank', 'Derrimut', 3)
('Brimbank', 'Hillside', 1)
('Brimbank', 'Kealba', 17)
('Brimbank', 'Keilor', 5)
('Brimbank', 'Keilor Downs', 11)
('Brimbank', 'Keilor East', 2)
('Brimbank', 'Keilor Lodge', 1)
('Brimbank', 'Keilor Park', 21)
('Brimbank', 'Kings Park', 4)
('Brimbank', 'St Albans', 20)
('Brimbank', 'Sunshine', 109)
('Brimbank', 'Sunshine North', 60)
('Brimbank', 'Sunshine West', 81)
('Brimbank', 'Sydenham', 5)
('Brimbank', 'Taylors Lakes', 18)
('Cardinia', 'Beaconsfield', 2)
('Cardinia', 'Beaconsfield Upper', 1)
('Cardinia', 'Emerald', 1)
('Cardinia', 'Officer', 1)
('Cardinia', 'Pakenham', 3)
('Casey', 'Berwick', 11)
('Casey', 'Cranbourne', 2)
('Casey', 'Cranbourne North', 2)
('Casey', 'Doveton', 5)
('Casey', 'Endeavour Hills', 5)
('Casey', 'Hallam', 4)
('Casey', 'Hampton Park', 3)
('Casey', 'Narre Warren', 6)
('Darebin', 'Alphington', 25)
('Darebin', 'Bundoora', 2)
('Darebin', 'Coburg North', 1)
('Darebin', 'Fairfield', 35)
('Darebin', 'Kingsbury', 13)
('Darebin', 'Northcote', 175)
('Darebin', 'Preston', 228)
('Darebin', 'Reservoir', 323)
('Darebin', 'Thornbury', 132)
('Frankston', 'Carrum Downs', 7)
('Frankston', 'Frankston', 16)
('Frankston', 'Frankston North', 3)
('Frankston', 'Frankston South', 7)
('Frankston', 'Langwarrin', 5)
('Frankston', 'Sandhurst', 1)
('Frankston', 'Seaford', 12)
('Frankston', 'Skye', 2)
('Glen Eira', 'Bentleigh', 131)
('Glen Eira', 'Bentleigh East', 234)
('Glen Eira', 'Brighton East', 4)
('Glen Eira', 'Carnegie', 138)
('Glen Eira', 'Caulfield', 12)
('Glen Eira', 'Caulfield East', 8)
('Glen Eira', 'Caulfield North', 35)
('Glen Eira', 'Caulfield South', 45)
('Glen Eira', 'Elsternwick', 59)
('Glen Eira', 'Elwood', 1)
('Glen Eira', 'Gardenvale', 6)
('Glen Eira', 'Glen Huntly', 16)
('Glen Eira', 'McKinnon', 5)
('Glen Eira', 'Murrumbeena', 80)
('Glen Eira', 'Ormond', 74)
('Greater Dandenong', 'Dandenong', 11)
('Greater Dandenong', 'Dandenong North', 13)
('Greater Dandenong', 'Keysborough', 9)
('Greater Dandenong', 'Noble Park', 12)
('Greater Dandenong', 'Springvale', 6)
('Greater Dandenong', 'Springvale South', 1)
('Hobsons Bay', 'Altona', 69)
('Hobsons Bay', 'Altona Meadows', 4)
('Hobsons Bay', 'Altona North', 49)
('Hobsons Bay', 'Brooklyn', 7)
('Hobsons Bay', 'Newport', 129)
('Hobsons Bay', 'Seabrook', 3)
('Hobsons Bay', 'Seaholme', 6)
('Hobsons Bay', 'South Kingsville', 22)
('Hobsons Bay', 'Spotswood', 27)
('Hobsons Bay', 'Williamstown', 100)
('Hobsons Bay', 'Williamstown North', 18)
('Hume', 'Broadmeadows', 17)
('Hume', 'Campbellfield', 3)
('Hume', 'Coolaroo', 2)
('Hume', 'Craigieburn', 31)
('Hume', 'Dallas', 4)
('Hume', 'Fawkner', 1)
('Hume', 'Gladstone Park', 12)
('Hume', 'Greenvale', 15)
('Hume', 'Jacana', 22)
('Hume', 'Meadow Heights', 11)
('Hume', 'Roxburgh Park', 7)
('Hume', 'Sunbury', 17)
('Hume', 'Tullamarine', 11)
('Hume', 'Westmeadows', 11)
('Kingston', 'Aspendale', 4)
('Kingston', 'Aspendale Gardens', 2)
('Kingston', 'Bonbeach', 1)
('Kingston', 'Carrum', 9)
('Kingston', 'Chelsea', 4)
('Kingston', 'Chelsea Heights', 2)
('Kingston', 'Cheltenham', 26)
('Kingston', 'Clarinda', 2)
('Kingston', 'Clayton South', 3)
('Kingston', 'Dingley Village', 16)
('Kingston', 'Edithvale', 5)
('Kingston', 'Hampton East', 2)
('Kingston', 'Highett', 4)
('Kingston', 'Mentone', 16)
('Kingston', 'Moorabbin', 60)
('Kingston', 'Mordialloc', 15)
('Kingston', 'Oakleigh South', 18)
('Kingston', 'Parkdale', 17)
('Kingston', 'Waterways', 1)
('Knox', 'Bayswater', 12)
('Knox', 'Boronia', 12)
('Knox', 'Ferntree Gully', 14)
('Knox', 'Knoxfield', 4)
('Knox', 'Rowville', 10)
('Knox', 'Scoresby', 5)
('Knox', 'The Basin', 3)
('Knox', 'Wantirna', 7)
('Knox', 'Wantirna South', 13)
('Macedon Ranges', 'Bullengarook', 1)
('Macedon Ranges', 'Gisborne', 5)
('Macedon Ranges', 'Riddells Creek', 1)
('Manningham', 'Bulleen', 65)
('Manningham', 'Doncaster', 108)
('Manningham', 'Doncaster East', 27)
('Manningham', 'Donvale', 8)
('Manningham', 'Templestowe', 15)
('Manningham', 'Templestowe Lower', 84)
('Manningham', 'Warrandyte', 3)
('Manningham', 'Wonga Park', 1)
('Maribyrnong', 'Braybrook', 44)
('Maribyrnong', 'Footscray', 126)
('Maribyrnong', 'Kingsville', 30)
('Maribyrnong', 'Maidstone', 90)
('Maribyrnong', 'Maribyrnong', 92)
('Maribyrnong', 'Seddon', 60)
('Maribyrnong', 'West Footscray', 96)
('Maribyrnong', 'Yarraville', 154)
('Maroondah', 'Bayswater North', 5)
('Maroondah', 'Croydon', 25)
('Maroondah', 'Croydon Hills', 2)
('Maroondah', 'Croydon North', 6)
('Maroondah', 'Croydon South', 1)
('Maroondah', 'Heathmont', 11)
('Maroondah', 'Kilsyth', 1)
('Maroondah', 'Ringwood', 13)
('Maroondah', 'Ringwood East', 9)
('Maroondah', 'Ringwood North', 7)
('Melbourne', 'Carlton', 48)
('Melbourne', 'Docklands', 3)
('Melbourne', 'East Melbourne', 22)
('Melbourne', 'Flemington', 1)
('Melbourne', 'Kensington', 111)
('Melbourne', 'Melbourne', 46)
('Melbourne', 'North Melbourne', 76)
('Melbourne', 'Parkville', 31)
('Melbourne', 'Port Melbourne', 23)
('Melbourne', 'South Yarra', 40)
('Melbourne', 'Southbank', 40)
('Melbourne', 'West Melbourne', 29)
('Melton', 'Brookfield', 1)
('Melton', 'Burnside Heights', 2)
('Melton', 'Caroline Springs', 9)
('Melton', 'Diggers Rest', 2)
('Melton', 'Hillside', 12)
('Melton', 'Kurunjang', 4)
('Melton', 'Melton', 8)
('Melton', 'Melton South', 15)
('Melton', 'Melton West', 5)
('Melton', 'Rockbank', 1)
('Melton', 'Taylors Hill', 7)
('Monash', 'Ashwood', 45)
('Monash', 'Burwood', 14)
('Monash', 'Chadstone', 34)
('Monash', 'Clayton', 11)
('Monash', 'Glen Waverley', 26)
('Monash', 'Hughesdale', 35)
('Monash', 'Huntingdale', 4)
('Monash', 'Mount Waverley', 44)
('Monash', 'Mulgrave', 18)
('Monash', 'Notting Hill', 2)
('Monash', 'Oakleigh', 43)
('Monash', 'Oakleigh East', 10)
('Monash', 'Oakleigh South', 34)
('Monash', 'Wheelers Hill', 13)
('Moonee Valley', 'Aberfeldie', 40)
('Moonee Valley', 'Airport West', 61)
('Moonee Valley', 'Ascot Vale', 125)
('Moonee Valley', 'Avondale Heights', 73)
('Moonee Valley', 'Essendon', 208)
('Moonee Valley', 'Essendon North', 20)
('Moonee Valley', 'Essendon West', 26)
('Moonee Valley', 'Flemington', 54)
('Moonee Valley', 'Keilor East', 100)
('Moonee Valley', 'Kensington', 5)
('Moonee Valley', 'Moonee Ponds', 139)
('Moonee Valley', 'Niddrie', 73)
('Moonee Valley', 'Strathmore', 58)
('Moonee Valley', 'Strathmore Heights', 5)
('Moonee Valley', 'Travancore', 10)
('Moorabool', 'Bacchus Marsh', 1)
('Moreland', 'Brunswick', 208)
('Moreland', 'Brunswick East', 80)
('Moreland', 'Brunswick West', 102)
('Moreland', 'Coburg', 176)
('Moreland', 'Coburg North', 53)
('Moreland', 'Fawkner', 96)
('Moreland', 'Fitzroy North', 3)
('Moreland', 'Glenroy', 144)
('Moreland', 'Gowanbrae', 21)
('Moreland', 'Hadfield', 61)
('Moreland', 'Oak Park', 58)
('Moreland', 'Pascoe Vale', 161)
('Nillumbik', 'Diamond Creek', 3)
('Nillumbik', 'Eltham', 19)
('Nillumbik', 'Eltham North', 7)
('Nillumbik', 'Greensborough', 5)
('Nillumbik', 'Hurstbridge', 1)
('Nillumbik', 'North Warrandyte', 1)
('Port Phillip', 'Albert Park', 64)
('Port Phillip', 'Balaclava', 25)
('Port Phillip', 'Elwood', 125)
('Port Phillip', 'Middle Park', 31)
('Port Phillip', 'Port Melbourne', 117)
('Port Phillip', 'Ripponlea', 9)
('Port Phillip', 'South Melbourne', 76)
('Port Phillip', 'Southbank', 1)
('Port Phillip', 'St Kilda', 160)
('Port Phillip', 'Windsor', 20)
('Stonnington', 'Armadale', 86)
('Stonnington', 'Glen Iris', 55)
('Stonnington', 'Kooyong', 1)
('Stonnington', 'Malvern', 62)
('Stonnington', 'Malvern East', 111)
('Stonnington', 'Prahran', 113)
('Stonnington', 'South Yarra', 157)
('Stonnington', 'Toorak', 99)
('Stonnington', 'Windsor', 35)
('Unavailable', 'Hampton', 1)
('Whitehorse', 'Blackburn', 13)
('Whitehorse', 'Blackburn North', 7)
('Whitehorse', 'Blackburn South', 8)
('Whitehorse', 'Box Hill', 54)
('Whitehorse', 'Burwood', 61)
('Whitehorse', 'Burwood East', 12)
('Whitehorse', 'Forest Hill', 14)
('Whitehorse', 'Mitcham', 19)
('Whitehorse', 'Mont Albert', 30)
('Whitehorse', 'Nunawading', 18)
('Whitehorse', 'Surrey Hills', 50)
('Whitehorse', 'Vermont', 10)
('Whitehorse', 'Vermont South', 8)
('Whittlesea', 'Bundoora', 10)
('Whittlesea', 'Doreen', 3)
('Whittlesea', 'Epping', 38)
('Whittlesea', 'Lalor', 28)
('Whittlesea', 'Mernda', 6)
('Whittlesea', 'Mill Park', 33)
('Whittlesea', 'South Morang', 18)
('Whittlesea', 'Thomastown', 24)
('Whittlesea', 'Whittlesea', 1)
('Whittlesea', 'Wollert', 6)
('Wyndham', 'Hoppers Crossing', 23)
('Wyndham', 'Point Cook', 9)
('Wyndham', 'Tarneit', 9)
('Wyndham', 'Truganina', 4)
('Wyndham', 'Werribee', 37)
('Wyndham', 'Williams Landing', 1)
('Wyndham', 'Wyndham Vale', 3)
('Yarra', 'Abbotsford', 55)
('Yarra', 'Alphington', 7)
('Yarra', 'Burnley', 7)
('Yarra', 'Carlton North', 44)
('Yarra', 'Clifton Hill', 52)
('Yarra', 'Collingwood', 62)
('Yarra', 'Cremorne', 24)
('Yarra', 'Fairfield', 4)
('Yarra', 'Fitzroy', 53)
('Yarra', 'Fitzroy North', 84)
('Yarra', 'Princes Hill', 4)
('Yarra', 'Richmond', 251)
('Yarra Ranges', 'Chirnside Park', 2)
('Yarra Ranges', 'Healesville', 1)
('Yarra Ranges', 'Montrose', 1)
('Yarra Ranges', 'Mooroolbark', 9)
('Yarra Ranges', 'Mount Evelyn', 1)
('Yarra Ranges', 'Silvan', 2)
('Yarra Ranges', 'Upwey', 1)
('Yarra Ranges', 'Yarra Glen', 1)

**Combinamos los datasets de ambas tablas ingestadas utilizando el comando JOIN de SQL para obtener un resultado similar a lo realizado con Pandas en clase.**

In [ ]:
with engine.connect() as con:
      rs = con.execute("SELECT monthly_price FROM airbnb WHERE monthly_price IS NOT null")
      print()
      for row in rs:
          print(row)

2022-07-11 21:00:20,710 INFO sqlalchemy.engine.Engine SELECT monthly_price FROM airbnb WHERE monthly_price IS NOT null
2022-07-11 21:00:20,712 INFO sqlalchemy.engine.Engine [raw sql] ()

(803.0,)
(4452.0,)
(920.0,)
(1900.0,)
(1400.0,)
(1540.0,)
(5572.0,)
(5100.0,)
(1150.0,)
(1000.0,)
(1100.0,)
(4172.0,)
(3000.0,)
(4000.0,)
(1260.0,)
(1500.0,)
(800.0,)
(8648.0,)
(3612.0,)
(1900.0,)
(2800.0,)
(657.0,)
(4900.0,)
(750.0,)
(2400.0,)
(3892.0,)
(980.0,)
(4300.0,)
(3400.0,)
(3400.0,)
(1300.0,)
(1200.0,)
(2250.0,)
(3862.0,)
(2320.0,)
(2500.0,)
(2000.0,)
(2500.0,)
(3300.0,)
(3400.0,)
(3892.0,)
(3600.0,)
(3200.0,)
(15000.0,)
(1250.0,)
(3436.0,)
(2700.0,)
(1080.0,)
(3850.0,)
(4200.0,)
(5572.0,)
(3632.0,)
(2500.0,)
(4000.0,)
(1800.0,)
(1900.0,)
(6245.0,)
(3185.0,)
(3750.0,)
(1775.0,)
(9000.0,)
(1450.0,)
(4410.0,)
(1960.0,)
(2800.0,)
(2900.0,)
(4500.0,)
(2436.0,)
(4410.0,)
(4867.0,)
(2252.0,)
(3000.0,)
(975.0,)
(3763.0,)
(5931.0,)
(800.0,)
(3800.0,)
(5300.0,)
(900.0,)
(3900.0,)
(4715.0,)
(4258.0,)
(4410.0,)
(8998.0,)
(4410.0,)
(4410.0,)
(6972.0,)
(9576.0,)
(6048.0,)
(2400.0,)
(2600.0,)
(6944.0,)
(5852.0,)
(5999.0,)
(1100.0,)
(3900.0,)
(4106.0,)
(4867.0,)
(6972.0,)
(1750.0,)
(1500.0,)
(4180.0,)
(5779.0,)
(2677.0,)
(1764.0,)
(1288.0,)
(6000.0,)
(850.0,)
(2000.0,)
(4000.0,)
(6000.0,)
(5040.0,)
(4106.0,)
(2281.0,)
(1950.0,)
(2700.0,)
(1000.0,)
(3500.0,)
(2500.0,)
(6000.0,)
(1850.0,)
(3000.0,)
(2700.0,)
(2300.0,)
(4100.0,)
(2600.0,)
(3000.0,)
(1500.0,)
(2400.0,)
(5600.0,)
(2500.0,)
(1200.0,)
(1590.0,)
(54258.0,)
(1800.0,)
(3900.0,)
(1250.0,)
(2500.0,)
(3080.0,)
(4172.0,)
(4500.0,)
(1000.0,)
(3200.0,)
(6000.0,)
(3585.0,)
(1400.0,)
(4500.0,)
(700.0,)
(3275.0,)
(1600.0,)
(1150.0,)
(4000.0,)
(9000.0,)
(3400.0,)
(4590.0,)
(4590.0,)
(3950.0,)
(2500.0,)
(3255.0,)
(2500.0,)
(1000.0,)
(3600.0,)
(1700.0,)
(2000.0,)
(2000.0,)
(2000.0,)
(5572.0,)
(2600.0,)
(3892.0,)
(3500.0,)
(1600.0,)
(1550.0,)
(1790.0,)
(2460.0,)
(3300.0,)
(2100.0,)
(8000.0,)
(9000.0,)
(4400.0,)
(3150.0,)
(2300.0,)
(2300.0,)
(4800.0,)
(4258.0,)
(4258.0,)
(3600.0,)
(1850.0,)
(1700.0,)
(2400.0,)
(2062.0,)
(3800.0,)
(1200.0,)
(3895.0,)
(2200.0,)
(3185.0,)
(4990.0,)
(1200.0,)
(1930.0,)
(2100.0,)
(2400.0,)
(2800.0,)
(2750.0,)
(8200.0,)
(4000.0,)
(3200.0,)
(1200.0,)
(3400.0,)
(3200.0,)
(2300.0,)
(4388.0,)
(1827.0,)
(1699.0,)
(2400.0,)
(950.0,)
(7967.0,)
(760.0,)
(3600.0,)
(7594.0,)
(3000.0,)
(7470.0,)
(2200.0,)
(2000.0,)
(1840.0,)
(1800.0,)
(2200.0,)
(1400.0,)
(6501.0,)
(3800.0,)
(8000.0,)
(2295.0,)
(3292.0,)
(8000.0,)
(1450.0,)
(10200.0,)
(3900.0,)
(1400.0,)
(9100.0,)
(2200.0,)
(1850.0,)
(5040.0,)
(3500.0,)
(2889.0,)
(2245.0,)
(2000.0,)
(2100.0,)
(1350.0,)
(2100.0,)
(4106.0,)
(995.0,)
(1600.0,)
(2400.0,)
(1680.0,)
(3995.0,)
(1100.0,)
(2000.0,)
(3795.0,)
(1176.0,)
(1500.0,)
(2880.0,)
(2800.0,)
(4000.0,)
(3850.0,)
(6400.0,)
(900.0,)
(3200.0,)
(2800.0,)
(2500.0,)
(1600.0,)
(3500.0,)
(3500.0,)
(1800.0,)
(1300.0,)
(1775.0,)
(1775.0,)
(1620.0,)
(5900.0,)
(2850.0,)
(3860.0,)
(4000.0,)
(4750.0,)
(2000.0,)
(2000.0,)
(3999.0,)
(3649.0,)
(3200.0,)
(2320.0,)
(3317.0,)
(3512.0,)
(4872.0,)
(1500.0,)
(3200.0,)
(5999.0,)
(1800.0,)
(2800.0,)
(3640.0,)
(3000.0,)
(3500.0,)
(3995.0,)
(17004.0,)
(4200.0,)
(4500.0,)
(2500.0,)
(1400.0,)
(1999.0,)
(2300.0,)
(2960.0,)
(4000.0,)
(1800.0,)
(1400.0,)
(2803.0,)
(4560.0,)
(3500.0,)
(4910.0,)
(3000.0,)
(2917.0,)
(2500.0,)
(1900.0,)
(4680.0,)
(5000.0,)
(4000.0,)
(3990.0,)
(1000.0,)
(1974.0,)
(2980.0,)
(2000.0,)
(800.0,)
(2600.0,)
(850.0,)
(2400.0,)
(3650.0,)
(9750.0,)
(3000.0,)
(4000.0,)
(3900.0,)
(3000.0,)
(2499.0,)
(1255.0,)
(2226.0,)
(1800.0,)
(2500.0,)
(1800.0,)
(3995.0,)
(3100.0,)
(2400.0,)
(3500.0,)
(2520.0,)
(3240.0,)
(4900.0,)
(1900.0,)
(6000.0,)
(1217.0,)
(3700.0,)
(2600.0,)
(3640.0,)
(3500.0,)
(3795.0,)
(4101.0,)
(2900.0,)
(4800.0,)
(2380.0,)
(1600.0,)
(4715.0,)
(2952.0,)
(1210.0,)
(1380.0,)
(1500.0,)
(8000.0,)
(4200.0,)
(1440.0,)
(5900.0,)
(2299.0,)
(4000.0,)
(1100.0,)
(2112.0,)
(1200.0,)
(1480.0,)
(3990.0,)
(770.0,)
(3400.0,)
(4100.0,)
(4200.0,)
(5350.0,)
(942.0,)
(3500.0,)
(4500.0,)
(1365.0,)
(1500.0,)
(3736.0,)
(5000.0,)
(5700.0,)
(1500.0,)
(1150.0,)
(2225.0,)
(3900.0,)
(1100.0,)
(2200.0,)
(4001.0,)
(2200.0,)
(3200.0,)
(3300.0,)
(2800.0,)
(1500.0,)
(3950.0,)
(11011.0,)
(7057.0,)
(15513.0,)
(1596.0,)
(1350.0,)
(3000.0,)
(4000.0,)
(4950.0,)
(1500.0,)
(3000.0,)
(3499.0,)
(5000.0,)
(3100.0,)
(6692.0,)
(4995.0,)
(1750.0,)
(3645.0,)
(1350.0,)
(1900.0,)
(2100.0,)
(3200.0,)
(4563.0,)
(4000.0,)
(5597.0,)
(4500.0,)
(4000.0,)
(3500.0,)
(2900.0,)
(1500.0,)
(2100.0,)
(6000.0,)
(2170.0,)
(2200.0,)
(1500.0,)
(3500.0,)
(2699.0,)
(2000.0,)
(5500.0,)
(3640.0,)
(850.0,)
(4200.0,)
(3750.0,)
(6000.0,)
(3700.0,)
(4100.0,)
(3500.0,)
(1900.0,)
(1800.0,)
(1099.0,)
(9100.0,)
(4600.0,)
(1400.0,)
(3800.0,)
(3000.0,)
(3300.0,)
(3800.0,)
(1500.0,)
(3300.0,)
(3488.0,)
(3400.0,)
(2120.0,)
(3802.0,)
(1300.0,)
(3018.0,)
(3200.0,)
(5800.0,)
(1594.0,)
(1100.0,)
(3000.0,)
(2604.0,)
(1645.0,)
(2400.0,)
(2050.0,)
(2600.0,)
(2990.0,)
(4199.0,)
(1100.0,)
(1600.0,)
(5590.0,)
(2800.0,)
(4936.0,)
(3000.0,)
(5800.0,)
(2100.0,)
(850.0,)
(3900.0,)
(4000.0,)
(4185.0,)
(2850.0,)
(3950.0,)
(3450.0,)
(1200.0,)
(3000.0,)
(2907.0,)
(2500.0,)
(2699.0,)
(3612.0,)
(3150.0,)
(3400.0,)
(3500.0,)
(1200.0,)
(3900.0,)
(7000.0,)
(1700.0,)
(2500.0,)
(1250.0,)
(4400.0,)
(1400.0,)
(3600.0,)
(1561.0,)
(3045.0,)
(2850.0,)
(4500.0,)
(5627.0,)
(3300.0,)
(2200.0,)
(4600.0,)
(7200.0,)
(2548.0,)
(3500.0,)
(8000.0,)
(7500.0,)
(2900.0,)
(3988.0,)
(2310.0,)
(4500.0,)
(3900.0,)
(3149.0,)
(2400.0,)
(1100.0,)
(2800.0,)
(2600.0,)
(2133.0,)
(2800.0,)
(3499.0,)
(1200.0,)
(9366.0,)
(3800.0,)
(3400.0,)
(3600.0,)
(1300.0,)
(3600.0,)
(2981.0,)
(1950.0,)
(4400.0,)
(3121.0,)
(3526.0,)
(3500.0,)
(3000.0,)
(3200.0,)
(2400.0,)
(3100.0,)
(1700.0,)
(3000.0,)
(3300.0,)
(1502.0,)
(1600.0,)
(1350.0,)
(20000.0,)
(1540.0,)
(3750.0,)
(1540.0,)
(7605.0,)
(3600.0,)
(2667.0,)
(1200.0,)
(5100.0,)
(3600.0,)
(2406.0,)
(2500.0,)
(4000.0,)
(1995.0,)
(2268.0,)
(2600.0,)
(4000.0,)
(4250.0,)
(1250.0,)
(3400.0,)
(2900.0,)
(1900.0,)
(4200.0,)
(2642.0,)
(6000.0,)
(1490.0,)
(2800.0,)
(14890.0,)
(620.0,)
(2000.0,)
(1500.0,)
(5800.0,)
(1000.0,)
(1200.0,)
(2900.0,)
(3125.0,)
(5500.0,)
(2800.0,)
(4500.0,)
(5900.0,)
(2248.0,)
(2997.0,)
(1670.0,)
(1780.0,)
(6083.0,)
(4840.0,)
(4995.0,)
(3000.0,)
(3925.0,)
(5500.0,)
(3500.0,)
(3500.0,)
(4800.0,)
(12775.0,)
(1800.0,)
(3999.0,)
(6599.0,)
(3750.0,)
(4998.0,)
(4000.0,)
(2755.0,)
(2700.0,)
(900.0,)
(3528.0,)
(2420.0,)
(3750.0,)
(3600.0,)
(1517.0,)
(3000.0,)
(3000.0,)
(1800.0,)
(2000.0,)
(1960.0,)
(4500.0,)
(3000.0,)
(3476.0,)
(3612.0,)
(700.0,)
(6000.0,)
(3200.0,)
(5779.0,)
(1600.0,)
(3995.0,)
(7990.0,)
(4250.0,)
(2850.0,)
(3200.0,)
(600.0,)
(5500.0,)
(3100.0,)
(2500.0,)
(2000.0,)
(3800.0,)
(2000.0,)
(1200.0,)
(4395.0,)
(23056.0,)
(4867.0,)
(2850.0,)
(5166.0,)
(4903.0,)
(4500.0,)
(2200.0,)
(2700.0,)
(2400.0,)
(11741.0,)
(1654.0,)
(1600.0,)
(8900.0,)
(1680.0,)
(3000.0,)
(2900.0,)
(1050.0,)
(2800.0,)
(870.0,)
(1550.0,)
(1900.0,)
(3800.0,)
(1000.0,)
(5500.0,)
(9000.0,)
(1920.0,)
(1300.0,)
(3350.0,)
(1241.0,)
(1600.0,)
(3200.0,)
(3000.0,)
(2800.0,)
(2400.0,)
(9212.0,)
(3700.0,)
(4000.0,)
(3500.0,)
(1690.0,)
(2667.0,)
(2480.0,)
(1239.0,)
(1200.0,)
(5000.0,)
(14722.0,)
(1600.0,)
(2019.0,)
(9000.0,)
(2801.0,)
(4200.0,)
(7900.0,)
(2300.0,)
(7168.0,)
(6944.0,)
(2200.0,)
(6000.0,)
(4000.0,)
(6000.0,)
(2000.0,)
(2400.0,)
(3601.0,)
(6844.0,)
(4000.0,)
(3000.0,)
(12000.0,)
(3605.0,)
(2150.0,)
(3400.0,)
(25000.0,)
(6000.0,)
(6000.0,)
(3855.0,)
(4272.0,)
(1523.0,)
(1200.0,)
(3450.0,)
(2293.0,)
(2800.0,)
(6000.0,)
(1440.0,)
(1700.0,)
(3501.0,)
(5995.0,)
(2450.0,)
(3080.0,)
(1000.0,)
(7707.0,)
(2300.0,)
(800.0,)
(949.0,)
(1517.0,)
(5000.0,)
(4000.0,)
(3454.0,)
(6975.0,)
(1280.0,)
(1100.0,)
(2380.0,)
(5870.0,)
(5200.0,)
(1990.0,)
(3700.0,)
(7000.0,)
(940.0,)
(1040.0,)
(4003.0,)
(2600.0,)
(1500.0,)
(6000.0,)
(3700.0,)
(6225.0,)
(3200.0,)
(2001.0,)
(400.0,)
(3640.0,)
(3000.0,)
(4197.0,)
(2900.0,)
(5712.0,)
(4000.0,)
(2500.0,)
(4500.0,)
(5000.0,)
(3000.0,)
(1218.0,)
(4600.0,)
(2503.0,)
(2800.0,)
(2750.0,)
(4800.0,)
(3500.0,)
(3500.0,)
(2000.0,)
(2500.0,)
(2280.0,)
(3000.0,)
(2000.0,)
(33641.0,)
(2450.0,)
(3500.0,)
(4000.0,)
(2583.0,)
(22000.0,)
(2100.0,)
(1100.0,)
(2501.0,)
(4517.0,)
(1800.0,)
(1600.0,)
(3000.0,)
(1090.0,)
(4000.0,)
(3600.0,)
(5779.0,)
(1700.0,)
(1900.0,)
(2900.0,)
(1800.0,)
(5779.0,)
(1332.0,)
(3950.0,)
(2550.0,)
(3200.0,)
(3318.0,)
(1400.0,)
(4990.0,)
(2200.0,)
(5000.0,)
(1974.0,)
(7500.0,)
(3800.0,)
(2800.0,)
(5931.0,)
(3100.0,)
(5550.0,)
(2000.0,)
(1750.0,)
(3600.0,)
(2700.0,)
(2250.0,)
(1500.0,)
(3461.0,)
(1000.0,)
(3000.0,)
(1176.0,)
(2400.0,)
(2058.0,)
(1250.0,)
(3000.0,)
(3650.0,)
(2800.0,)
(2000.0,)
(1800.0,)
(1533.0,)
(1700.0,)
(1000.0,)
(4000.0,)
(4200.0,)
(7980.0,)
(3364.0,)
(4925.0,)
(2400.0,)
(2606.0,)
(2999.0,)
(9954.0,)
(3000.0,)
(6000.0,)
(1900.0,)
(1200.0,)
(882.0,)
(3000.0,)
(3200.0,)
(2100.0,)
(1400.0,)
(1800.0,)
(1900.0,)
(5500.0,)
(6500.0,)
(1600.0,)
(1801.0,)
(3999.0,)
(650.0,)
(3480.0,)
(1238.0,)
(5400.0,)
(2500.0,)
(2800.0,)
(2200.0,)
(3276.0,)
(6900.0,)
(2900.0,)
(3300.0,)
(1400.0,)
(3200.0,)
(4503.0,)
(4450.0,)
(4800.0,)
(2500.0,)
(1300.0,)
(2079.0,)
(1380.0,)
(3799.0,)
(2730.0,)
(3950.0,)
(2800.0,)
(850.0,)
(7812.0,)
(7952.0,)
(7700.0,)
(10000.0,)
(5280.0,)
(1300.0,)
(3150.0,)
(5999.0,)
(980.0,)
(3300.0,)
(1800.0,)
(2730.0,)
(3332.0,)
(4100.0,)
(2415.0,)
(2300.0,)
(3995.0,)
(800.0,)
(4400.0,)
(2800.0,)
(3509.0,)
(4977.0,)
(6000.0,)
(3276.0,)
(2660.0,)
(3780.0,)
(4000.0,)
(2500.0,)
(3000.0,)
(4000.0,)
(4680.0,)
(2501.0,)
(5250.0,)
(2000.0,)
(1932.0,)
(8000.0,)
(5940.0,)
(2500.0,)
(3500.0,)
(1911.0,)
(2399.0,)
(2950.0,)
(3500.0,)
(3100.0,)
(955.0,)
(2250.0,)
(2000.0,)
(1800.0,)
(527.0,)
(1100.0,)
(2800.0,)
(2025.0,)
(5599.0,)
(7770.0,)
(999.0,)
(3360.0,)
(1100.0,)
(7000.0,)
(1800.0,)
(3800.0,)
(3780.0,)
(2380.0,)
(2380.0,)
(2660.0,)
(2912.0,)
(2968.0,)
(3332.0,)
(3192.0,)
(3192.0,)
(2184.0,)
(3388.0,)
(3388.0,)
(4088.0,)
(4088.0,)
(4312.0,)
(4760.0,)
(4536.0,)
(4760.0,)
(750.0,)
(800.0,)
(3900.0,)
(1650.0,)
(1365.0,)
(3500.0,)
(3500.0,)
(5000.0,)
(2750.0,)
(4899.0,)
(1560.0,)
(1200.0,)
(4200.0,)
(3900.0,)
(2400.0,)
(4000.0,)
(4689.0,)
(2250.0,)
(2400.0,)
(2417.0,)
(4600.0,)
(1150.0,)
(1500.0,)
(1800.0,)
(2592.0,)
(6000.0,)
(3500.0,)
(3955.0,)
(6000.0,)
(4263.0,)
(3999.0,)
(3199.0,)
(2000.0,)
(1550.0,)
(2000.0,)
(3600.0,)
(1100.0,)
(1100.0,)
(4400.0,)
(5000.0,)
(2000.0,)
(1900.0,)
(3369.0,)
(1100.0,)
(1100.0,)
(3298.0,)
(1500.0,)
(4500.0,)
(4500.0,)
(4000.0,)
(1650.0,)
(1400.0,)
(14000.0,)
(2400.0,)
(1101.0,)
(1150.0,)
(3000.0,)
(2600.0,)
(2800.0,)
(1300.0,)
(4500.0,)
(7540.0,)
(4200.0,)
(1200.0,)
(6880.0,)
(3444.0,)
(1100.0,)
(4400.0,)
(1200.0,)
(5498.0,)
(3404.0,)
(1300.0,)
(2500.0,)
(12999.0,)
(1600.0,)
(1500.0,)
(4880.0,)
(1200.0,)
(700.0,)
(4000.0,)
(4500.0,)
(1900.0,)
(1100.0,)
(4000.0,)
(3100.0,)
(2559.0,)
(6500.0,)
(3500.0,)
(4452.0,)
(1200.0,)
(5200.0,)
(3800.0,)
(2000.0,)
(5780.0,)
(2200.0,)
(3900.0,)
(2102.0,)
(4088.0,)
(1549.0,)
(3099.0,)
(1001.0,)
(3609.0,)
(3500.0,)
(1600.0,)
(3334.0,)
(2399.0,)
(3200.0,)
(5500.0,)
(14509.0,)
(2500.0,)
(714.0,)
(3460.0,)
(3300.0,)
(3297.0,)
(2000.0,)
(3500.0,)
(3800.0,)
(2000.0,)
(3500.0,)
(3350.0,)
(3500.0,)
(5000.0,)
(2945.0,)
(6200.0,)
(875.0,)
(3800.0,)
(1600.0,)
(1100.0,)
(9600.0,)
(4200.0,)
(950.0,)
(11500.0,)
(1950.0,)
(2000.0,)
(15000.0,)
(2000.0,)
(5250.0,)
(1395.0,)
(2300.0,)
(3004.0,)
(4900.0,)
(3241.0,)
(3000.0,)
(3000.0,)
(4600.0,)
(3595.0,)
(2000.0,)
(1690.0,)
(2500.0,)
(2200.0,)
(1950.0,)
(3750.0,)
(900.0,)
(1750.0,)
(2077.0,)
(2500.0,)
(1200.0,)
(5000.0,)
(3200.0,)
(2560.0,)
(7999.0,)
(2000.0,)
(1800.0,)
(1400.0,)
(3600.0,)
(2300.0,)
(2077.0,)
(4172.0,)
(2500.0,)
(1800.0,)
(2205.0,)
(1200.0,)
(2000.0,)
(3000.0,)
(2500.0,)
(3000.0,)
(1119.0,)
(527.0,)
(4800.0,)
(920.0,)
(1850.0,)
(2000.0,)
(2150.0,)
(600.0,)
(2800.0,)
(1472.0,)
(5000.0,)
(684.0,)
(3200.0,)
(1200.0,)
(1200.0,)
(2000.0,)
(2101.0,)
(6480.0,)
(650.0,)
(1000.0,)
(840.0,)
(2163.0,)
(3595.0,)
(1600.0,)
(2700.0,)
(11990.0,)
(850.0,)
(3350.0,)
(3715.0,)
(6200.0,)
(2373.0,)
(1450.0,)
(1500.0,)
(4948.0,)
(683.0,)
(1500.0,)
(2000.0,)
(950.0,)
(2769.0,)
(2303.0,)
(800.0,)
(4500.0,)
(2801.0,)
(682.0,)
(2500.0,)
(1230.0,)
(1820.0,)
(4400.0,)
(3509.0,)
(3400.0,)
(3000.0,)
(2854.0,)
(1800.0,)
(546.0,)
(2001.0,)
(4000.0,)
(682.0,)
(17216.0,)
(4500.0,)
(682.0,)
(2500.0,)
(3250.0,)
(1230.0,)
(750.0,)
(682.0,)
(6200.0,)
(1262.0,)
(1599.0,)
(7990.0,)
(1800.0,)
(2800.0,)
(2483.0,)
(17320.0,)
(1384.0,)
(950.0,)
(1000.0,)
(652.0,)
(1083.0,)
(2600.0,)
(3300.0,)
(3000.0,)
(3080.0,)
(2151.0,)
(1250.0,)
(2900.0,)
(1100.0,)
(3600.0,)
(2900.0,)
(1200.0,)
(3204.0,)
(4000.0,)
(5101.0,)
(1994.0,)
(2562.0,)
(1300.0,)
(36835.0,)
(550.0,)
(4580.0,)
(2399.0,)
(2100.0,)
(2769.0,)
(1200.0,)
(5750.0,)
(3516.0,)
(1000.0,)
(2950.0,)
(3500.0,)
(1500.0,)
(1300.0,)
(1380.0,)
(4400.0,)
(1800.0,)
(1029.0,)
(5500.0,)
(3633.0,)
(1000.0,)
(2514.0,)
(4500.0,)
(1200.0,)
(5750.0,)
(2500.0,)
(2200.0,)
(7000.0,)
(9277.0,)
(3150.0,)
(3500.0,)
(800.0,)
(2000.0,)
(2400.0,)
(3612.0,)
(2900.0,)
(1085.0,)
(600.0,)
(3066.0,)
(850.0,)
(3285.0,)
(2415.0,)
(1400.0,)
(700.0,)
(1330.0,)
(4201.0,)
(1050.0,)
(760.0,)
(1200.0,)
(1071.0,)
(1150.0,)
(4000.0,)
(1600.0,)
(800.0,)
(1100.0,)
(2330.0,)
(2800.0,)
(4200.0,)
(3980.0,)
(2500.0,)
(4400.0,)
(2800.0,)
(1200.0,)
(1850.0,)
(5000.0,)
(2356.0,)
(2600.0,)
(2000.0,)
(2961.0,)
(3900.0,)
(2252.0,)
(1554.0,)
(2700.0,)
(5100.0,)
(800.0,)
(1600.0,)
(2850.0,)
(3609.0,)
(5850.0,)
(3483.0,)
(1260.0,)
(1100.0,)
(5000.0,)
(3528.0,)
(1980.0,)
(1500.0,)
(1100.0,)
(4500.0,)
(2352.0,)
(2904.0,)
(8040.0,)
(1695.0,)
(8040.0,)
(3800.0,)
(1000.0,)
(1580.0,)
(3004.0,)
(2928.0,)
(2099.0,)
(2200.0,)
(1082.0,)
(2499.0,)
(2600.0,)
(3510.0,)
(2250.0,)
(1900.0,)
(4100.0,)
(750.0,)
(4000.0,)
(7500.0,)
(3100.0,)
(4500.0,)
(2499.0,)
(1869.0,)
(3347.0,)
(2700.0,)
(2800.0,)
(9000.0,)
(1800.0,)
(1400.0,)
(2600.0,)
(750.0,)
(999.0,)
(5990.0,)
(3500.0,)
(1200.0,)
(900.0,)
(5590.0,)
(4100.0,)
(1100.0,)
(1890.0,)
(2279.0,)
(1344.0,)
(2500.0,)
(600.0,)
(1100.0,)
(5800.0,)
(1974.0,)
(4000.0,)
(1300.0,)
(2700.0,)
(2400.0,)
(8000.0,)
(3899.0,)
(1200.0,)
(2200.0,)
(2500.0,)
(969.0,)
(630.0,)
(4000.0,)
(1000.0,)
(990.0,)
(4750.0,)
(3000.0,)
(3456.0,)
(1400.0,)
(3500.0,)
(4600.0,)
(1600.0,)
(1155.0,)
(4200.0,)
(3254.0,)
(3500.0,)
(10974.0,)
(2000.0,)
(24225.0,)
(18663.0,)
(1000.0,)
(1990.0,)
(3002.0,)
(3000.0,)
(3955.0,)
(8000.0,)
(600.0,)
(682.0,)
(3400.0,)
(600.0,)
(3200.0,)
(3000.0,)
(4200.0,)
(4600.0,)
(3088.0,)
(2500.0,)
(950.0,)
(1700.0,)
(1850.0,)
(2100.0,)
(3400.0,)
(2688.0,)
(11620.0,)
(3500.0,)
(4800.0,)
(7864.0,)
(880.0,)
(999.0,)
(1500.0,)
(2562.0,)
(3509.0,)
(2504.0,)
(1950.0,)
(4000.0,)
(2500.0,)
(3150.0,)
(5599.0,)
(800.0,)
(6000.0,)
(2999.0,)
(3380.0,)
(3160.0,)
(1600.0,)
(600.0,)
(2900.0,)
(2200.0,)
(3250.0,)
(1733.0,)
(4000.0,)
(6600.0,)
(1700.0,)
(6000.0,)
(2200.0,)
(7500.0,)
(1820.0,)
(2790.0,)
(2520.0,)
(1000.0,)
(1700.0,)
(2400.0,)
(2600.0,)
(2000.0,)
(3100.0,)
(1300.0,)
(1660.0,)
(3000.0,)
(2436.0,)
(3600.0,)
(1500.0,)
(1303.0,)
(900.0,)
(2800.0,)
(900.0,)
(3570.0,)
(3300.0,)
(1690.0,)
(1300.0,)
(1450.0,)
(1699.0,)
(3506.0,)
(2500.0,)
(1550.0,)
(527.0,)
(3001.0,)
(2900.0,)
(1080.0,)
(440.0,)
(4000.0,)
(2877.0,)
(3525.0,)
(3000.0,)
(2500.0,)
(3300.0,)
(750.0,)
(1009.0,)
(1343.0,)
(1764.0,)
(1050.0,)
(9100.0,)
(3000.0,)
(1000.0,)
(3347.0,)
(6132.0,)
(2345.0,)
(2500.0,)
(4900.0,)
(3666.0,)
(2400.0,)
(1100.0,)
(2399.0,)
(3672.0,)
(2100.0,)
(1799.0,)
(2300.0,)
(3695.0,)
(1071.0,)
(3497.0,)
(2800.0,)
(2000.0,)
(2800.0,)
(7500.0,)
(2000.0,)
(5572.0,)
(1500.0,)
(1000.0,)
(4000.0,)
(1512.0,)
(2000.0,)
(750.0,)
(2184.0,)
(1008.0,)
(1784.0,)
(2700.0,)
(3900.0,)
(3500.0,)
(1900.0,)
(1200.0,)
(2000.0,)
(2000.0,)
(2835.0,)
(1600.0,)
(1180.0,)
(2500.0,)
(609.0,)
(1200.0,)
(3780.0,)
(7000.0,)
(2600.0,)
(900.0,)
(750.0,)
(3500.0,)
(3600.0,)
(3516.0,)
(7502.0,)
(10260.0,)
(900.0,)
(2955.0,)
(2000.0,)
(3570.0,)
(3800.0,)
(1650.0,)
(2604.0,)
(2800.0,)
(1400.0,)
(2690.0,)
(1600.0,)
(3950.0,)
(1250.0,)
(1250.0,)
(3551.0,)
(2900.0,)
(6699.0,)
(4900.0,)
(2299.0,)
(3200.0,)
(3347.0,)
(3955.0,)
(3955.0,)
(1400.0,)
(3956.0,)
(3347.0,)
(1000.0,)
(3850.0,)
(5500.0,)
(2394.0,)
(2250.0,)
(3469.0,)
(1200.0,)
(3600.0,)
(1680.0,)
(1920.0,)
(3465.0,)
(2400.0,)
(2400.0,)
(1500.0,)
(7900.0,)
(3750.0,)
(2400.0,)
(800.0,)
(920.0,)
(2470.0,)
(1180.0,)
(3200.0,)
(3400.0,)
(3333.0,)
(600.0,)
(780.0,)
(1750.0,)
(3100.0,)
(1704.0,)
(5000.0,)
(3360.0,)
(3500.0,)
(3500.0,)
(2500.0,)
(13000.0,)
(1000.0,)
(4011.0,)
(3369.0,)
(3502.0,)
(3200.0,)
(7000.0,)
(1600.0,)
(1250.0,)
(1218.0,)
(1200.0,)
(4705.0,)
(700.0,)
(1200.0,)
(2859.0,)
(3060.0,)
(3000.0,)
(3770.0,)
(860.0,)
(3000.0,)
(800.0,)
(4000.0,)
(7300.0,)
(2688.0,)
(1800.0,)
(8800.0,)
(3333.0,)
(2536.0,)
(3469.0,)
(2251.0,)
(5000.0,)
(2650.0,)
(10002.0,)
(1850.0,)
(1200.0,)
(1150.0,)
(2808.0,)
(4500.0,)
(700.0,)
(900.0,)
(1260.0,)
(2300.0,)
(1764.0,)
(1481.0,)
(1100.0,)
(1200.0,)
(1950.0,)
(2500.0,)
(8000.0,)
(2100.0,)
(7000.0,)
(2800.0,)
(1350.0,)
(4500.0,)
(4535.0,)
(2701.0,)
(3501.0,)
(1110.0,)
(1075.0,)
(2501.0,)
(5186.0,)
(861.0,)
(2900.0,)
(5600.0,)
(1650.0,)
(1560.0,)
(1476.0,)
(3300.0,)
(940.0,)
(4500.0,)
(2299.0,)
(3101.0,)
(2550.0,)
(5010.0,)
(4290.0,)
(4301.0,)
(1999.0,)
(1950.0,)
(1865.0,)
(3650.0,)
(4095.0,)
(2019.0,)
(2300.0,)
(1701.0,)
(5100.0,)
(2200.0,)
(3700.0,)
(4600.0,)
(2800.0,)
(2450.0,)
(2800.0,)
(3200.0,)
(2100.0,)
(1900.0,)
(2300.0,)
(1000.0,)
(2170.0,)
(2499.0,)
(2500.0,)
(903.0,)
(2200.0,)
(6000.0,)
(8060.0,)
(1241.0,)
(900.0,)
(3315.0,)
(1300.0,)
(3600.0,)
(4000.0,)
(770.0,)
(4500.0,)
(3700.0,)
(3700.0,)
(5400.0,)
(2142.0,)
(3168.0,)
(1900.0,)
(3500.0,)
(1452.0,)
(2900.0,)
(2800.0,)
(4480.0,)
(3500.0,)
(2200.0,)
(1120.0,)
(2600.0,)
(4200.0,)
(1700.0,)
(1500.0,)
(4500.0,)
(5000.0,)
(2898.0,)
(2895.0,)
(5500.0,)
(2850.0,)
(1471.0,)
(1700.0,)
(4500.0,)
(4788.0,)
(2500.0,)
(772.0,)
(809.0,)
(3900.0,)
(3900.0,)
(4001.0,)
(3900.0,)
(960.0,)
(750.0,)
(1500.0,)
(1350.0,)
(4000.0,)
(1200.0,)
(1080.0,)
(3600.0,)
(1180.0,)
(6300.0,)
(2700.0,)
(1850.0,)
(5800.0,)
(1350.0,)
(800.0,)
(1365.0,)
(11000.0,)
(1800.0,)
(4199.0,)
(3000.0,)
(2667.0,)
(2800.0,)
(2877.0,)
(680.0,)
(7920.0,)
(1100.0,)
(2960.0,)
(4600.0,)
(2799.0,)
(1400.0,)
(527.0,)
(4562.0,)
(1503.0,)
(2000.0,)
(1500.0,)
(3500.0,)
(2688.0,)
(2289.0,)
(1813.0,)
(2669.0,)
(2600.0,)
(3888.0,)
(1500.0,)
(3300.0,)
(1730.0,)
(6200.0,)
(4400.0,)
(1120.0,)
(2499.0,)
(1500.0,)
(1800.0,)
(2800.0,)
(2400.0,)
(990.0,)
(1200.0,)
(2400.0,)
(903.0,)
(2000.0,)
(900.0,)
(1800.0,)
(1000.0,)
(1352.0,)
(2000.0,)
(2300.0,)
(730.0,)
(2587.0,)
(1100.0,)
(2851.0,)
(2700.0,)
(2501.0,)
(540.0,)
(1000.0,)
(850.0,)
(3209.0,)
(1239.0,)
(2465.0,)
(1008.0,)
(2000.0,)
(1599.0,)
(1500.0,)
(1602.0,)
(1638.0,)
(2199.0,)
(825.0,)
(1750.0,)
(700.0,)
(700.0,)
(700.0,)
(1440.0,)
(1440.0,)
(1440.0,)
(3000.0,)
(700.0,)
(700.0,)
(3469.0,)
(3469.0,)
(3300.0,)
(3000.0,)
(1566.0,)
(700.0,)
(1300.0,)
(4600.0,)
(1300.0,)
(2800.0,)
(700.0,)
(2299.0,)
(1550.0,)
(2000.0,)
(1990.0,)
(9000.0,)
(1000.0,)

In [ ]:
query5="""SELECT CAST(m.postcode AS int), CAST(a.zipcode AS int), a.price, a.weekly_price, a.monthly_price, m.price
FROM melb_data m
INNER JOIN airbnb a
ON m.postcode=a.zipcode
LIMIT 1000
"""

In [ ]:
with engine.connect() as con:
      rs = con.execute(query5)
      print(query5)
      for row in rs:
          print(row)

2022-07-11 21:00:21,840 INFO sqlalchemy.engine.Engine SELECT CAST(m.postcode AS int), CAST(a.zipcode AS int), a.price, a.weekly_price, a.monthly_price, m.price
FROM melb_data m
INNER JOIN airbnb a
ON m.postcode=a.zipcode
LIMIT 1000

2022-07-11 21:00:21,841 INFO sqlalchemy.engine.Engine [raw sql] ()
SELECT CAST(m.postcode AS int), CAST(a.zipcode AS int), a.price, a.weekly_price, a.monthly_price, m.price
FROM melb_data m
INNER JOIN airbnb a
ON m.postcode=a.zipcode
LIMIT 1000

(3105, 3105, 60, None, None, 599900.0)
(3105, 3105, 60, None, None, 760000.0)
(3105, 3105, 60, None, None, 787000.0)
(3105, 3105, 60, None, None, 794000.0)
(3105, 3105, 60, None, None, 812500.0)
(3105, 3105, 60, None, None, 833000.0)
(3105, 3105, 60, None, None, 851000.0)
(3105, 3105, 60, None, None, 860000.0)
(3105, 3105, 60, None, None, 880000.0)
(3105, 3105, 60, None, None, 890000.0)
(3105, 3105, 60, None, None, 903000.0)
(3105, 3105, 60, None, None, 905000.0)
(3105, 3105, 60, None, None, 910000.0)
(3105, 3105, 60, None, None, 950000.0)
(3105, 3105, 60, None, None, 975000.0)
(3105, 3105, 60, None, None, 976000.0)
(3105, 3105, 60, None, None, 980000.0)
(3105, 3105, 60, None, None, 980000.0)
(3105, 3105, 60, None, None, 980000.0)
(3105, 3105, 60, None, None, 990000.0)
(3105, 3105, 60, None, None, 990000.0)
(3105, 3105, 60, None, None, 1000000.0)
(3105, 3105, 60, None, None, 1002000.0)
(3105, 3105, 60, None, None, 1050000.0)
(3105, 3105, 60, None, None, 1060000.0)
(3105, 3105, 60, None, None, 1060000.0)
(3105, 3105, 60, None, None, 1063000.0)
(3105, 3105, 60, None, None, 1075000.0)
(3105, 3105, 60, None, None, 1085000.0)
(3105, 3105, 60, None, None, 1100000.0)
(3105, 3105, 60, None, None, 1100000.0)
(3105, 3105, 60, None, None, 1100000.0)
(3105, 3105, 60, None, None, 1110000.0)
(3105, 3105, 60, None, None, 1127000.0)
(3105, 3105, 60, None, None, 1140000.0)
(3105, 3105, 60, None, None, 1160000.0)
(3105, 3105, 60, None, None, 1200000.0)
(3105, 3105, 60, None, None, 1207000.0)
(3105, 3105, 60, None, None, 1225000.0)
(3105, 3105, 60, None, None, 1225000.0)
(3105, 3105, 60, None, None, 1230000.0)
(3105, 3105, 60, None, None, 1235000.0)
(3105, 3105, 60, None, None, 1240000.0)
(3105, 3105, 60, None, None, 1244000.0)
(3105, 3105, 60, None, None, 1250000.0)
(3105, 3105, 60, None, None, 1250000.0)
(3105, 3105, 60, None, None, 1260000.0)
(3105, 3105, 60, None, None, 1280000.0)
(3105, 3105, 60, None, None, 1300000.0)
(3105, 3105, 60, None, None, 1300000.0)
(3105, 3105, 60, None, None, 1300000.0)
(3105, 3105, 60, None, None, 1300000.0)
(3105, 3105, 60, None, None, 1302000.0)
(3105, 3105, 60, None, None, 1303000.0)
(3105, 3105, 60, None, None, 1310000.0)
(3105, 3105, 60, None, None, 1320000.0)
(3105, 3105, 60, None, None, 1320000.0)
(3105, 3105, 60, None, None, 1331000.0)
(3105, 3105, 60, None, None, 1336000.0)
(3105, 3105, 60, None, None, 1340000.0)
(3105, 3105, 60, None, None, 1351000.0)
(3105, 3105, 60, None, None, 1360000.0)
(3105, 3105, 60, None, None, 1400000.0)
(3105, 3105, 60, None, None, 1401000.0)
(3105, 3105, 60, None, None, 1475000.0)
(3105, 3105, 60, None, None, 1490000.0)
(3105, 3105, 60, None, None, 1505000.0)
(3105, 3105, 60, None, None, 1540000.0)
(3105, 3105, 60, None, None, 1580000.0)
(3105, 3105, 60, None, None, 1730000.0)
(3105, 3105, 60, None, None, 1751000.0)
(3057, 3057, 35, 200.0, 803.0, 290000.0)
(3057, 3057, 35, 200.0, 803.0, 320000.0)
(3057, 3057, 35, 200.0, 803.0, 370000.0)
(3057, 3057, 35, 200.0, 803.0, 385000.0)
(3057, 3057, 35, 200.0, 803.0, 390000.0)
(3057, 3057, 35, 200.0, 803.0, 390500.0)
(3057, 3057, 35, 200.0, 803.0, 400000.0)
(3057, 3057, 35, 200.0, 803.0, 420000.0)
(3057, 3057, 35, 200.0, 803.0, 435000.0)
(3057, 3057, 35, 200.0, 803.0, 435000.0)
(3057, 3057, 35, 200.0, 803.0, 445000.0)
(3057, 3057, 35, 200.0, 803.0, 460000.0)
(3057, 3057, 35, 200.0, 803.0, 480000.0)
(3057, 3057, 35, 200.0, 803.0, 500000.0)
(3057, 3057, 35, 200.0, 803.0, 501000.0)
(3057, 3057, 35, 200.0, 803.0, 510000.0)
(3057, 3057, 35, 200.0, 803.0, 522000.0)
(3057, 3057, 35, 200.0, 803.0, 550000.0)
(3057, 3057, 35, 200.0, 803.0, 570000.0)
(3057, 3057, 35, 200.0, 803.0, 570000.0)
(3057, 3057, 35, 200.0, 803.0, 570000.0)
(3057, 3057, 35, 200.0, 803.0, 570000.0)
(3057, 3057, 35, 200.0, 803.0, 580000.0)
(3057, 3057, 35, 200.0, 803.0, 590000.0)
(3057, 3057, 35, 200.0, 803.0, 615000.0)
(3057, 3057, 35, 200.0, 803.0, 620000.0)
(3057, 3057, 35, 200.0, 803.0, 632000.0)
(3057, 3057, 35, 200.0, 803.0, 656000.0)
(3057, 3057, 35, 200.0, 803.0, 665000.0)
(3057, 3057, 35, 200.0, 803.0, 675000.0)
(3057, 3057, 35, 200.0, 803.0, 683000.0)
(3057, 3057, 35, 200.0, 803.0, 690000.0)
(3057, 3057, 35, 200.0, 803.0, 702500.0)
(3057, 3057, 35, 200.0, 803.0, 771000.0)
(3057, 3057, 35, 200.0, 803.0, 800000.0)
(3057, 3057, 35, 200.0, 803.0, 805000.0)
(3057, 3057, 35, 200.0, 803.0, 825000.0)
(3057, 3057, 35, 200.0, 803.0, 835000.0)
(3057, 3057, 35, 200.0, 803.0, 856000.0)
(3057, 3057, 35, 200.0, 803.0, 892000.0)
(3057, 3057, 35, 200.0, 803.0, 899000.0)
(3057, 3057, 35, 200.0, 803.0, 910000.0)
(3057, 3057, 35, 200.0, 803.0, 930000.0)
(3057, 3057, 35, 200.0, 803.0, 937000.0)
(3057, 3057, 35, 200.0, 803.0, 940000.0)
(3057, 3057, 35, 200.0, 803.0, 950000.0)
(3057, 3057, 35, 200.0, 803.0, 957000.0)
(3057, 3057, 35, 200.0, 803.0, 959000.0)
(3057, 3057, 35, 200.0, 803.0, 970000.0)
(3057, 3057, 35, 200.0, 803.0, 975000.0)
(3057, 3057, 35, 200.0, 803.0, 998000.0)
(3057, 3057, 35, 200.0, 803.0, 1010000.0)
(3057, 3057, 35, 200.0, 803.0, 1015000.0)
(3057, 3057, 35, 200.0, 803.0, 1023000.0)
(3057, 3057, 35, 200.0, 803.0, 1024000.0)
(3057, 3057, 35, 200.0, 803.0, 1025000.0)
(3057, 3057, 35, 200.0, 803.0, 1050000.0)
(3057, 3057, 35, 200.0, 803.0, 1050000.0)
(3057, 3057, 35, 200.0, 803.0, 1065000.0)
(3057, 3057, 35, 200.0, 803.0, 1080000.0)
(3057, 3057, 35, 200.0, 803.0, 1105000.0)
(3057, 3057, 35, 200.0, 803.0, 1125000.0)
(3057, 3057, 35, 200.0, 803.0, 1170000.0)
(3057, 3057, 35, 200.0, 803.0, 1185000.0)
(3057, 3057, 35, 200.0, 803.0, 1210000.0)
(3057, 3057, 35, 200.0, 803.0, 1220000.0)
(3057, 3057, 35, 200.0, 803.0, 1265000.0)
(3057, 3057, 35, 200.0, 803.0, 1265000.0)
(3057, 3057, 35, 200.0, 803.0, 1280000.0)
(3057, 3057, 35, 200.0, 803.0, 1283000.0)
(3057, 3057, 35, 200.0, 803.0, 1290000.0)
(3057, 3057, 35, 200.0, 803.0, 1305000.0)
(3057, 3057, 35, 200.0, 803.0, 1310000.0)
(3057, 3057, 35, 200.0, 803.0, 1310000.0)
(3057, 3057, 35, 200.0, 803.0, 1325000.0)
(3057, 3057, 35, 200.0, 803.0, 1330000.0)
(3057, 3057, 35, 200.0, 803.0, 1335000.0)
(3057, 3057, 35, 200.0, 803.0, 1350000.0)
(3057, 3057, 35, 200.0, 803.0, 1495000.0)
(3057, 3057, 35, 200.0, 803.0, 1500000.0)
(3057, 3057, 35, 200.0, 803.0, 1550000.0)
(3057, 3057, 35, 200.0, 803.0, 1574000.0)
(3057, 3057, 35, 200.0, 803.0, 1600000.0)
(3057, 3057, 35, 200.0, 803.0, 1615000.0)
(3057, 3057, 35, 200.0, 803.0, 1625000.0)
(3057, 3057, 35, 200.0, 803.0, 1679000.0)
(3057, 3057, 35, 200.0, 803.0, 1815000.0)
(3057, 3057, 35, 200.0, 803.0, 1900000.0)
(3182, 3182, 159, 1253.0, 4452.0, 320000.0)
(3182, 3182, 159, 1253.0, 4452.0, 320000.0)
(3182, 3182, 159, 1253.0, 4452.0, 330000.0)
(3182, 3182, 159, 1253.0, 4452.0, 335000.0)
(3182, 3182, 159, 1253.0, 4452.0, 346000.0)
(3182, 3182, 159, 1253.0, 4452.0, 350000.0)
(3182, 3182, 159, 1253.0, 4452.0, 350000.0)
(3182, 3182, 159, 1253.0, 4452.0, 354000.0)
(3182, 3182, 159, 1253.0, 4452.0, 360000.0)
(3182, 3182, 159, 1253.0, 4452.0, 360000.0)
(3182, 3182, 159, 1253.0, 4452.0, 360000.0)
(3182, 3182, 159, 1253.0, 4452.0, 365000.0)
(3182, 3182, 159, 1253.0, 4452.0, 366000.0)
(3182, 3182, 159, 1253.0, 4452.0, 370500.0)
(3182, 3182, 159, 1253.0, 4452.0, 380000.0)
(3182, 3182, 159, 1253.0, 4452.0, 380000.0)
(3182, 3182, 159, 1253.0, 4452.0, 385000.0)
(3182, 3182, 159, 1253.0, 4452.0, 385000.0)
(3182, 3182, 159, 1253.0, 4452.0, 390000.0)
(3182, 3182, 159, 1253.0, 4452.0, 392000.0)
(3182, 3182, 159, 1253.0, 4452.0, 395000.0)
(3182, 3182, 159, 1253.0, 4452.0, 400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 420000.0)
(3182, 3182, 159, 1253.0, 4452.0, 420000.0)
(3182, 3182, 159, 1253.0, 4452.0, 430000.0)
(3182, 3182, 159, 1253.0, 4452.0, 430000.0)
(3182, 3182, 159, 1253.0, 4452.0, 430000.0)
(3182, 3182, 159, 1253.0, 4452.0, 431000.0)
(3182, 3182, 159, 1253.0, 4452.0, 435000.0)
(3182, 3182, 159, 1253.0, 4452.0, 450000.0)
(3182, 3182, 159, 1253.0, 4452.0, 450000.0)
(3182, 3182, 159, 1253.0, 4452.0, 450000.0)
(3182, 3182, 159, 1253.0, 4452.0, 451000.0)
(3182, 3182, 159, 1253.0, 4452.0, 451000.0)
(3182, 3182, 159, 1253.0, 4452.0, 452000.0)
(3182, 3182, 159, 1253.0, 4452.0, 455000.0)
(3182, 3182, 159, 1253.0, 4452.0, 459000.0)
(3182, 3182, 159, 1253.0, 4452.0, 460000.0)
(3182, 3182, 159, 1253.0, 4452.0, 461000.0)
(3182, 3182, 159, 1253.0, 4452.0, 465000.0)
(3182, 3182, 159, 1253.0, 4452.0, 468000.0)
(3182, 3182, 159, 1253.0, 4452.0, 470000.0)
(3182, 3182, 159, 1253.0, 4452.0, 470000.0)
(3182, 3182, 159, 1253.0, 4452.0, 470000.0)
(3182, 3182, 159, 1253.0, 4452.0, 475000.0)
(3182, 3182, 159, 1253.0, 4452.0, 475000.0)
(3182, 3182, 159, 1253.0, 4452.0, 475000.0)
(3182, 3182, 159, 1253.0, 4452.0, 480000.0)
(3182, 3182, 159, 1253.0, 4452.0, 481000.0)
(3182, 3182, 159, 1253.0, 4452.0, 481000.0)
(3182, 3182, 159, 1253.0, 4452.0, 482000.0)
(3182, 3182, 159, 1253.0, 4452.0, 482300.0)
(3182, 3182, 159, 1253.0, 4452.0, 487500.0)
(3182, 3182, 159, 1253.0, 4452.0, 495000.0)
(3182, 3182, 159, 1253.0, 4452.0, 500000.0)
(3182, 3182, 159, 1253.0, 4452.0, 500000.0)
(3182, 3182, 159, 1253.0, 4452.0, 500000.0)
(3182, 3182, 159, 1253.0, 4452.0, 500000.0)
(3182, 3182, 159, 1253.0, 4452.0, 503500.0)
(3182, 3182, 159, 1253.0, 4452.0, 509000.0)
(3182, 3182, 159, 1253.0, 4452.0, 517500.0)
(3182, 3182, 159, 1253.0, 4452.0, 520000.0)
(3182, 3182, 159, 1253.0, 4452.0, 520000.0)
(3182, 3182, 159, 1253.0, 4452.0, 520000.0)
(3182, 3182, 159, 1253.0, 4452.0, 525000.0)
(3182, 3182, 159, 1253.0, 4452.0, 530000.0)
(3182, 3182, 159, 1253.0, 4452.0, 530000.0)
(3182, 3182, 159, 1253.0, 4452.0, 533000.0)
(3182, 3182, 159, 1253.0, 4452.0, 535000.0)
(3182, 3182, 159, 1253.0, 4452.0, 535000.0)
(3182, 3182, 159, 1253.0, 4452.0, 540000.0)
(3182, 3182, 159, 1253.0, 4452.0, 542500.0)
(3182, 3182, 159, 1253.0, 4452.0, 550000.0)
(3182, 3182, 159, 1253.0, 4452.0, 560000.0)
(3182, 3182, 159, 1253.0, 4452.0, 561000.0)
(3182, 3182, 159, 1253.0, 4452.0, 565000.0)
(3182, 3182, 159, 1253.0, 4452.0, 570000.0)
(3182, 3182, 159, 1253.0, 4452.0, 570000.0)
(3182, 3182, 159, 1253.0, 4452.0, 571000.0)
(3182, 3182, 159, 1253.0, 4452.0, 575000.0)
(3182, 3182, 159, 1253.0, 4452.0, 575000.0)
(3182, 3182, 159, 1253.0, 4452.0, 580000.0)
(3182, 3182, 159, 1253.0, 4452.0, 580000.0)
(3182, 3182, 159, 1253.0, 4452.0, 582000.0)
(3182, 3182, 159, 1253.0, 4452.0, 586500.0)
(3182, 3182, 159, 1253.0, 4452.0, 600000.0)
(3182, 3182, 159, 1253.0, 4452.0, 602000.0)
(3182, 3182, 159, 1253.0, 4452.0, 610000.0)
(3182, 3182, 159, 1253.0, 4452.0, 610000.0)
(3182, 3182, 159, 1253.0, 4452.0, 610000.0)
(3182, 3182, 159, 1253.0, 4452.0, 610500.0)
(3182, 3182, 159, 1253.0, 4452.0, 615000.0)
(3182, 3182, 159, 1253.0, 4452.0, 616000.0)
(3182, 3182, 159, 1253.0, 4452.0, 640000.0)
(3182, 3182, 159, 1253.0, 4452.0, 640000.0)
(3182, 3182, 159, 1253.0, 4452.0, 648000.0)
(3182, 3182, 159, 1253.0, 4452.0, 650000.0)
(3182, 3182, 159, 1253.0, 4452.0, 680000.0)
(3182, 3182, 159, 1253.0, 4452.0, 685000.0)
(3182, 3182, 159, 1253.0, 4452.0, 690000.0)
(3182, 3182, 159, 1253.0, 4452.0, 700000.0)
(3182, 3182, 159, 1253.0, 4452.0, 701000.0)
(3182, 3182, 159, 1253.0, 4452.0, 720000.0)
(3182, 3182, 159, 1253.0, 4452.0, 730000.0)
(3182, 3182, 159, 1253.0, 4452.0, 750000.0)
(3182, 3182, 159, 1253.0, 4452.0, 757500.0)
(3182, 3182, 159, 1253.0, 4452.0, 760000.0)
(3182, 3182, 159, 1253.0, 4452.0, 785000.0)
(3182, 3182, 159, 1253.0, 4452.0, 808000.0)
(3182, 3182, 159, 1253.0, 4452.0, 875000.0)
(3182, 3182, 159, 1253.0, 4452.0, 875000.0)
(3182, 3182, 159, 1253.0, 4452.0, 902000.0)
(3182, 3182, 159, 1253.0, 4452.0, 902000.0)
(3182, 3182, 159, 1253.0, 4452.0, 920000.0)
(3182, 3182, 159, 1253.0, 4452.0, 920000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1000000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1000000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1000000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1030000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1077000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1100000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1120000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1120000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1180000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1190000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1200500.0)
(3182, 3182, 159, 1253.0, 4452.0, 1210000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1220000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1225000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1250000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1295000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1301000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1316000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1361000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1365000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1435000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1440000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1500000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1600000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1600000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1650000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1678000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1891000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1900000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1900000.0)
(3182, 3182, 159, 1253.0, 4452.0, 1950000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2000000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2000000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2000000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2220000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2260000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2455000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2680000.0)
(3182, 3182, 159, 1253.0, 4452.0, 2720000.0)
(3182, 3182, 159, 1253.0, 4452.0, 4400000.0)
(3182, 3182, 159, 1253.0, 4452.0, 4750000.0)
(3182, 3182, 159, 1253.0, 4452.0, 5046000.0)
(3071, 3071, 50, 250.0, 920.0, 245000.0)
(3071, 3071, 50, 250.0, 920.0, 260000.0)
(3071, 3071, 50, 250.0, 920.0, 270000.0)
(3071, 3071, 50, 250.0, 920.0, 277500.0)
(3071, 3071, 50, 250.0, 920.0, 295000.0)
(3071, 3071, 50, 250.0, 920.0, 300000.0)
(3071, 3071, 50, 250.0, 920.0, 303500.0)
(3071, 3071, 50, 250.0, 920.0, 315000.0)
(3071, 3071, 50, 250.0, 920.0, 328000.0)
(3071, 3071, 50, 250.0, 920.0, 330000.0)
(3071, 3071, 50, 250.0, 920.0, 332000.0)
(3071, 3071, 50, 250.0, 920.0, 350000.0)
(3071, 3071, 50, 250.0, 920.0, 365000.0)
(3071, 3071, 50, 250.0, 920.0, 370000.0)
(3071, 3071, 50, 250.0, 920.0, 371000.0)
(3071, 3071, 50, 250.0, 920.0, 383000.0)
(3071, 3071, 50, 250.0, 920.0, 415000.0)
(3071, 3071, 50, 250.0, 920.0, 432500.0)
(3071, 3071, 50, 250.0, 920.0, 435000.0)
(3071, 3071, 50, 250.0, 920.0, 438000.0)
(3071, 3071, 50, 250.0, 920.0, 450000.0)
(3071, 3071, 50, 250.0, 920.0, 450000.0)
(3071, 3071, 50, 250.0, 920.0, 462000.0)
(3071, 3071, 50, 250.0, 920.0, 466000.0)
(3071, 3071, 50, 250.0, 920.0, 470000.0)
(3071, 3071, 50, 250.0, 920.0, 486000.0)
(3071, 3071, 50, 250.0, 920.0, 493000.0)
(3071, 3071, 50, 250.0, 920.0, 505000.0)
(3071, 3071, 50, 250.0, 920.0, 505000.0)
(3071, 3071, 50, 250.0, 920.0, 510000.0)
(3071, 3071, 50, 250.0, 920.0, 510000.0)
(3071, 3071, 50, 250.0, 920.0, 517500.0)
(3071, 3071, 50, 250.0, 920.0, 525500.0)
(3071, 3071, 50, 250.0, 920.0, 560000.0)
(3071, 3071, 50, 250.0, 920.0, 571750.0)
(3071, 3071, 50, 250.0, 920.0, 600000.0)
(3071, 3071, 50, 250.0, 920.0, 601000.0)
(3071, 3071, 50, 250.0, 920.0, 605000.0)
(3071, 3071, 50, 250.0, 920.0, 700000.0)
(3071, 3071, 50, 250.0, 920.0, 701000.0)
(3071, 3071, 50, 250.0, 920.0, 716000.0)
(3071, 3071, 50, 250.0, 920.0, 740000.0)
(3071, 3071, 50, 250.0, 920.0, 745000.0)
(3071, 3071, 50, 250.0, 920.0, 756000.0)
(3071, 3071, 50, 250.0, 920.0, 760000.0)
(3071, 3071, 50, 250.0, 920.0, 795000.0)
(3071, 3071, 50, 250.0, 920.0, 805000.0)
(3071, 3071, 50, 250.0, 920.0, 865000.0)
(3071, 3071, 50, 250.0, 920.0, 865000.0)
(3071, 3071, 50, 250.0, 920.0, 874000.0)
(3071, 3071, 50, 250.0, 920.0, 880000.0)
(3071, 3071, 50, 250.0, 920.0, 887000.0)
(3071, 3071, 50, 250.0, 920.0, 891000.0)
(3071, 3071, 50, 250.0, 920.0, 898000.0)
(3071, 3071, 50, 250.0, 920.0, 900000.0)
(3071, 3071, 50, 250.0, 920.0, 900000.0)
(3071, 3071, 50, 250.0, 920.0, 905000.0)
(3071, 3071, 50, 250.0, 920.0, 910000.0)
(3071, 3071, 50, 250.0, 920.0, 910500.0)
(3071, 3071, 50, 250.0, 920.0, 915000.0)
(3071, 3071, 50, 250.0, 920.0, 920000.0)
(3071, 3071, 50, 250.0, 920.0, 925000.0)
(3071, 3071, 50, 250.0, 920.0, 928500.0)
(3071, 3071, 50, 250.0, 920.0, 940000.0)
(3071, 3071, 50, 250.0, 920.0, 944000.0)
(3071, 3071, 50, 250.0, 920.0, 960000.0)
(3071, 3071, 50, 250.0, 920.0, 970000.0)
(3071, 3071, 50, 250.0, 920.0, 972000.0)
(3071, 3071, 50, 250.0, 920.0, 995000.0)
(3071, 3071, 50, 250.0, 920.0, 998000.0)
(3071, 3071, 50, 250.0, 920.0, 1000000.0)
(3071, 3071, 50, 250.0, 920.0, 1000000.0)
(3071, 3071, 50, 250.0, 920.0, 1010000.0)
(3071, 3071, 50, 250.0, 920.0, 1020000.0)
(3071, 3071, 50, 250.0, 920.0, 1031000.0)
(3071, 3071, 50, 250.0, 920.0, 1070000.0)
(3071, 3071, 50, 250.0, 920.0, 1080000.0)
(3071, 3071, 50, 250.0, 920.0, 1085000.0)
(3071, 3071, 50, 250.0, 920.0, 1100000.0)
(3071, 3071, 50, 250.0, 920.0, 1100000.0)
(3071, 3071, 50, 250.0, 920.0, 1100000.0)
(3071, 3071, 50, 250.0, 920.0, 1110000.0)
(3071, 3071, 50, 250.0, 920.0, 1110000.0)
(3071, 3071, 50, 250.0, 920.0, 1110000.0)
(3071, 3071, 50, 250.0, 920.0, 1130000.0)
(3071, 3071, 50, 250.0, 920.0, 1135000.0)
(3071, 3071, 50, 250.0, 920.0, 1143000.0)
(3071, 3071, 50, 250.0, 920.0, 1160000.0)
(3071, 3071, 50, 250.0, 920.0, 1164000.0)
(3071, 3071, 50, 250.0, 920.0, 1190000.0)
(3071, 3071, 50, 250.0, 920.0, 1195000.0)
(3071, 3071, 50, 250.0, 920.0, 1200000.0)
(3071, 3071, 50, 250.0, 920.0, 1200000.0)
(3071, 3071, 50, 250.0, 920.0, 1200000.0)
(3071, 3071, 50, 250.0, 920.0, 1200000.0)
(3071, 3071, 50, 250.0, 920.0, 1200000.0)
(3071, 3071, 50, 250.0, 920.0, 1200000.0)
(3071, 3071, 50, 250.0, 920.0, 1205500.0)
(3071, 3071, 50, 250.0, 920.0, 1210000.0)
(3071, 3071, 50, 250.0, 920.0, 1211000.0)
(3071, 3071, 50, 250.0, 920.0, 1225000.0)
(3071, 3071, 50, 250.0, 920.0, 1235000.0)
(3071, 3071, 50, 250.0, 920.0, 1236000.0)
(3071, 3071, 50, 250.0, 920.0, 1240000.0)
(3071, 3071, 50, 250.0, 920.0, 1245000.0)
(3071, 3071, 50, 250.0, 920.0, 1250000.0)
(3071, 3071, 50, 250.0, 920.0, 1250000.0)
(3071, 3071, 50, 250.0, 920.0, 1260000.0)
(3071, 3071, 50, 250.0, 920.0, 1265000.0)
(3071, 3071, 50, 250.0, 920.0, 1271000.0)
(3071, 3071, 50, 250.0, 920.0, 1272000.0)
(3071, 3071, 50, 250.0, 920.0, 1275000.0)
(3071, 3071, 50, 250.0, 920.0, 1280000.0)
(3071, 3071, 50, 250.0, 920.0, 1280000.0)
(3071, 3071, 50, 250.0, 920.0, 1290000.0)
(3071, 3071, 50, 250.0, 920.0, 1300000.0)
(3071, 3071, 50, 250.0, 920.0, 1345000.0)
(3071, 3071, 50, 250.0, 920.0, 1346000.0)
(3071, 3071, 50, 250.0, 920.0, 1370000.0)
(3071, 3071, 50, 250.0, 920.0, 1375000.0)
(3071, 3071, 50, 250.0, 920.0, 1380000.0)
(3071, 3071, 50, 250.0, 920.0, 1400000.0)
(3071, 3071, 50, 250.0, 920.0, 1400000.0)
(3071, 3071, 50, 250.0, 920.0, 1420000.0)
(3071, 3071, 50, 250.0, 920.0, 1427000.0)
(3071, 3071, 50, 250.0, 920.0, 1428888.0)
(3071, 3071, 50, 250.0, 920.0, 1430000.0)
(3071, 3071, 50, 250.0, 920.0, 1430000.0)
(3071, 3071, 50, 250.0, 920.0, 1450000.0)
(3071, 3071, 50, 250.0, 920.0, 1460000.0)
(3071, 3071, 50, 250.0, 920.0, 1478000.0)
(3071, 3071, 50, 250.0, 920.0, 1570000.0)
(3071, 3071, 50, 250.0, 920.0, 1605000.0)
(3071, 3071, 50, 250.0, 920.0, 1620000.0)
(3071, 3071, 50, 250.0, 920.0, 1626000.0)
(3071, 3071, 50, 250.0, 920.0, 1635000.0)
(3071, 3071, 50, 250.0, 920.0, 1750000.0)
(3071, 3071, 50, 250.0, 920.0, 1913000.0)
(3071, 3071, 50, 250.0, 920.0, 2070000.0)
(3183, 3183, 69, 400.0, 1900.0, 280000.0)
(3183, 3183, 69, 400.0, 1900.0, 290000.0)

## Ejercicio 2: 

1. Seleccionar un subconjunto de columnas que les parezcan relevantes al problema de predicción del valor de la propiedad. Justificar las columnas seleccionadas y las que no lo fueron.
 - Eliminar los valores extremos que no sean relevantes para la predicción de valores de las propiedades.

2. Agregar información adicional respectiva al entorno de una propiedad a partir del [conjunto de datos de AirBnB](https://www.kaggle.com/tylerx/melbourne-airbnb-open-data?select=cleansed_listings_dec18.csv) utilizado en el práctico. 
  1. Seleccionar qué variables agregar y qué combinaciones aplicar a cada una. Por ejemplo, pueden utilizar solo la columna `price`, o aplicar múltiples transformaciones como la mediana o el mínimo.
  1. Utilizar la variable zipcode para unir los conjuntos de datos. Sólo incluir los zipcodes que tengan una cantidad mínima de registros (a elección) como para que la información agregada sea relevante.
  2. Investigar al menos otras 2 variables que puedan servir para combinar los datos, y justificar si serían adecuadas o no. Pueden asumir que cuentan con la ayuda de anotadores expertos para encontrar equivalencias entre barrios o direcciones, o que cuentan con algoritmos para encontrar las n ubicaciones más cercanas a una propiedad a partir de sus coordenadas geográficas. **NO** es necesario que realicen la implementación.

Pueden leer otras columnas del conjunto de AirBnB además de las que están en `interesting_cols`, si les parecen relevantes.

Primero obtenemos la descripción de todas las columnas:

Rooms: Number of rooms

Price: Price in dollars

Method: S - property sold; SP - property sold prior; PI - property passed in; PN - sold prior not disclosed; SN - sold not disclosed; NB - no bid; VB - vendor bid; W - withdrawn prior to auction; SA - sold after auction; SS - sold after auction price not disclosed. N/A - price or highest bid not available.

Type: br - bedroom(s); h - house,cottage,villa, semi,terrace; u - unit, duplex; t - townhouse; dev site - development site; o res - other residential.

SellerG: Real Estate Agent

Date: Date sold

Distance: Distance from CBD

Regionname: General Region (West, North West, North, North east …etc)

Propertycount: Number of properties that exist in the suburb.

Bedroom2 : Scraped # of Bedrooms (from different source)

Bathroom: Number of Bathrooms

Car: Number of carspots

Landsize: Land Size

BuildingArea: Building Size

CouncilArea: Governing council for the area

Las columnas que consideramos importantes para una futura predicción del precio de una propiedad son:
- Rooms, Bedroom2 y bathrooms: Se escogieron estas tres variables ya que se considera que cuanto mayor es la cantidad de habitaciones/baños que tenga la casa, mayor será el precio de la misma. 
- Distance: 
- Landsize: se considera importante esta variable para poder analizar la incidencia del tamaño del terreno el el precio de la casa. 
- BuildingArea: La superficie de edificación sin duda sera una variable que incida en el precio final de una casa. 
- Car: 
- YearBuilt: se elige la variable Yearbuilt ya que se presupone una relación entre la edad de la casa y su precio. 


Y el Precio para evaluar futuras predicciones.

Para filtrar los valores extremos **Numericos** utilizamos el método de los 3 sigmas: filtramos los valores por encima o por debajo de 3 desvios estandar de la media.

Para filtrar los valores extremos **Categóricos**:
Para cada variable, ponderamos cada categoria calculando las frecuencias relativas. Luego, eliminamos los registros de aquellas categorias que tenian menos frecuencia relativa que un *0.5%*.

In [ ]:
melb_df = melbourne_df.copy()

In [ ]:
def filter_outliers_mask(df, cols, n_desvios_ = 3, verbosity = True):

  df_size = df.shape[0]

  idx_to_delete=[]

  for c in cols:
    print(c)
    media = df[c].mean()
    desvio = df[c].std()
    print(desvio/media)
    
    minimo, maximo = (media - n_desvios * desvio, media + n_desvios * desvio)
    
    mask = (df[c] < minimo) | (df[c] > maximo)

    idx_to_delete.append(list(df.loc[mask].index))
    
  idx_to_delete = numpy.array([item for sublist in idx_to_delete for item in sublist])

  if verbosity:
    print("DF Size", df_size)
    print(f"Eliminaremos un {numpy.round(len(idx_to_delete)/df_size * 100,1)}% de los registros")
    print("DF Processed size: ", df_size - len(idx_to_delete))

  
  return idx_to_delete

def filter_df(df, idx_to_delete):
  return df.drop(index = idx_to_delete)



def filter_categorical(df, cols, perc_of_cut = 0.005, verbosity = True):  
  df_size = df.shape[0]
  idx_to_delete=[]  

  for c in categorical_cols:   
    categories_count = df[c].value_counts()/df[c].count()
    categories_to_delete = categories_count[categories_count < perc_of_cut].index
    idx_to_delete_categorical = df[df[c].isin(categories_to_delete)].index
    idx_to_delete.append(idx_to_delete_categorical)
 
 
  idx_to_delete = numpy.array([item for sublist in idx_to_delete for item in sublist])

  if verbosity:
    print("DF Size", df_size)
    print(f"Eliminaremos un {numpy.round(len(idx_to_delete)/df_size * 100,1)}% de los registros")
    print("DF Processed size: ", df_size - len(idx_to_delete))

  
  return idx_to_delete

In [ ]:
categorical_cols = ['Type','CouncilArea']
numerical_cols = ['Rooms',  'Bedroom2', 'Bathroom','Distance',  'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Price']
n_desvios = 3

# Numerical filtering 3 sigma
print("Numerical\n")
idx_to_delete_numerical = filter_outliers_mask(melb_df, numerical_cols, n_desvios_ = n_desvios, verbosity = True)

# Categorical filtering
print("\n Categorical")
idx_to_delete_categorical = filter_categorical(melb_df, categorical_cols, perc_of_cut = 0.001, verbosity = True)

idx_to_delete = numpy.append(idx_to_delete_numerical, idx_to_delete_categorical)
idx_to_delete = numpy.unique(idx_to_delete)

Numerical

Rooms
0.32530595528008216
Bedroom2
0.33139326001719105
Bathroom
0.45084930122347244
Distance
0.5788966792346524
Car
0.5978809976183062
Landsize
7.146407581386584
BuildingArea
3.5600638558653595
YearBuilt
0.018971884592221013
Price
0.5943294471922271
DF Size 13580
Eliminaremos un 7.2% de los registros
DF Processed size:  12602

 Categorical
DF Size 13580
Eliminaremos un 0.1% de los registros
DF Processed size:  13563

In [ ]:
n_shape_inicial = melb_df.shape[0]
melb_df = filter_df(melb_df, idx_to_delete)

for c in numerical_cols:
  print(c)
  media = melb_df[c].mean()
  desvio = melb_df[c].std()
  print(desvio/media)

print(n_shape_inicial, '\n',melb_df.shape[0])
print(melb_df.shape[0] / n_shape_inicial)

Rooms
0.31322108880705063
Bedroom2
0.31325213104609373
Bathroom
0.4125850351983081
Distance
0.501147316698878
Car
0.5482800388684067
Landsize
1.241275257278208
BuildingArea
0.5832717349024185
YearBuilt
0.018381400091815128
Price
0.5042109126071634
13580
 12784
0.9413843888070692

**Seleccionamos qué variables agregar y qué combinaciones aplicar a cada una.**

En principio, agregaríamos las columnas: 
1.   price = "precio de alquiler por día" 
2.   weekly_price = "precio de alquiler por semana"
3.   monthly_price = "precio de alquiler por mes"
4.   zipcode = "Código postal"

con las siguientes transformaciones: 

1.   El valor mínimo, máximo y promedio de los precios
2.   El conteo de registros por cada zipcode ("zipcode_count")

In [ ]:
airbnb_df.zipcode.value_counts()[:5]

3000.0    2491
3000       876
3006.0     860
3182.0     579
3182       556
Name: zipcode, dtype: int64

In [ ]:
airbnb_df['zipcode'] = pandas.to_numeric(airbnb_df.zipcode, errors='coerce')

In [ ]:
airbnb_df.zipcode.value_counts().head(5)

3000.0    3367
3006.0    1268
3182.0    1135
3141.0     881
3004.0     728
Name: zipcode, dtype: int64

In [ ]:
relevant_cols = ['zipcode', 'price', 'weekly_price', 'monthly_price']
## Option 1
# Pass a dictionary where the keys are the original columns to aggregate and
# the values are the operations (or list of operations).
airbnb_price_by_zipcode = airbnb_df[relevant_cols].groupby('zipcode')\
  .agg({'price': ['min', 'mean', "max"], 'weekly_price': ['min', 'mean', "max"],
        'monthly_price': ['min', 'mean', "max"], "zipcode": "count"})\
  .reset_index()
# Flatten the two level columns
airbnb_price_by_zipcode.columns = [
  ' '.join(col).strip()
  for col in airbnb_price_by_zipcode.columns.values]
# Rename columns
airbnb_price_by_zipcode = airbnb_price_by_zipcode.rename(
    columns={'price min': "airbnb_price_min",
             'price mean': 'airbnb_price_mean',
             'price max':'airbnb_price_max',
             'weekly_price min': 'airbnb_weekly_price_min',
             'weekly_price mean': 'airbnb_weekly_price_mean',
             'weekly_price max': 'airbnb_weekly_price_max',
             'monthly_price min': 'airbnb_monthly_price_min',
             'monthly_price mean': 'airbnb_monthly_price_mean',
             'monthly_price max': 'airbnb_monthly_price_max',
             'zipcode count': 'zipcode_count',
                }
)
airbnb_price_by_zipcode

,zipcode,airbnb_price_min,airbnb_price_mean,airbnb_price_max,airbnb_weekly_price_min,airbnb_weekly_price_mean,airbnb_weekly_price_max,airbnb_monthly_price_min,airbnb_monthly_price_mean,airbnb_monthly_price_max,zipcode_count
0,2010.0,40,40.000000,40,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2134.0,50,50.000000,50,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2582.0,104,104.000000,104,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3000.0,0,150.504307,9000,150.0,918.738956,3325.0,550.0,3407.204651,8060.0,3367
4,3001.0,120,132.500000,145,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...
242,7367.0,230,230.000000,230,NaN,NaN,NaN,NaN,NaN,NaN,1
243,8938.0,296,296.000000,296,NaN,NaN,NaN,NaN,NaN,NaN,1
244,9004.0,226,226.000000,226,NaN,NaN,NaN,NaN,NaN,NaN,1
245,9540.0,245,245.000000,245,NaN,NaN,NaN,NaN,NaN,NaN,1
246,30122.0,75,75.000000,75,525.0,525.000000,525.0,2281.0,2281.000000,2281.0,1

**Utilizamos la variable zipcode para unir los conjuntos de datos.** Sólo incluimos los zipcodes que tengan una cantidad mínima de registros como para que la información agregada sea relevante.

Seleccionamos como cantidad mínima 25 registros (valor arbitrario cercano a la mediana).

In [ ]:
airbnb_price_by_zipcode["zipcode_count"].describe()

count     247.000000
mean       92.101215
std       261.914701
min         1.000000
25%         8.500000
50%        27.000000
75%        73.000000
max      3367.000000
Name: zipcode_count, dtype: float64

In [ ]:
n_registros = 25

airbnb_price_by_zipcode_min= airbnb_price_by_zipcode[airbnb_price_by_zipcode["zipcode_count"] >= n_registros]
airbnb_price_by_zipcode_min

,zipcode,airbnb_price_min,airbnb_price_mean,airbnb_price_max,airbnb_weekly_price_min,airbnb_weekly_price_mean,airbnb_weekly_price_max,airbnb_monthly_price_min,airbnb_monthly_price_mean,airbnb_monthly_price_max,zipcode_count
3,3000.0,0,150.504307,9000,150.0,918.738956,3325.0,550.0,3407.204651,8060.0,3367
5,3002.0,19,200.979695,1550,140.0,956.379310,2030.0,700.0,3712.714286,8000.0,197
6,3003.0,19,130.205993,550,362.0,760.200000,1388.0,1350.0,2629.500000,4689.0,267
7,3004.0,12,158.271978,1771,298.0,1061.171429,3200.0,1000.0,3759.925926,8998.0,728
8,3006.0,17,188.851735,2998,150.0,1239.827273,3500.0,1500.0,4358.556701,15000.0,1268
...,...,...,...,...,...,...,...,...,...,...,...
206,3788.0,86,249.370787,610,600.0,1547.500000,2445.0,2000.0,5441.500000,9000.0,89
214,3799.0,35,196.932584,750,173.0,992.666667,1740.0,609.0,2194.333333,4000.0,89
218,3805.0,30,225.235294,1101,380.0,622.000000,1106.0,1400.0,2178.666667,3736.0,34
219,3806.0,37,488.272727,12501,540.0,540.000000,540.0,NaN,NaN,NaN,33
233,3977.0,18,92.955556,341,198.0,422.000000,1000.0,950.0,1025.000000,1100.0,45

In [ ]:
merged_sales_df = melb_df.merge(
    airbnb_price_by_zipcode_min, how='left',
    left_on='Postcode', right_on='zipcode'
)
print("% de registros no intersectados ", numpy.round(merged_sales_df.zipcode.isnull().sum() / merged_sales_df.shape[0] * 100, 1), "%")
merged_sales_df.sample(10)

% de registros no intersectados  13.1 %

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,airbnb_price_min,airbnb_price_mean,airbnb_price_max,airbnb_weekly_price_min,airbnb_weekly_price_mean,airbnb_weekly_price_max,airbnb_monthly_price_min,airbnb_monthly_price_mean,airbnb_monthly_price_max,zipcode_count
1231,Brunswick,215/1 Dods St,3,u,1044000.0,S,Jellis,16/07/2016,5.2,3056.0,...,25.0,94.672646,599.0,170.0,618.758065,2700.0,600.0,2308.978723,4590.0,446.0
2903,Hampton,118 Ludstone St,2,h,1615000.0,SA,Chisholm,12/11/2016,13.7,3188.0,...,35.0,245.112676,898.0,250.0,1273.600000,5768.0,900.0,4694.555556,18663.0,71.0
5255,Rosanna,6/3 Prospect Rd,2,u,452000.0,S,Nelson,28/08/2016,11.4,3084.0,...,24.0,127.208333,732.0,250.0,1128.750000,3100.0,900.0,2298.000000,4500.0,72.0
5894,Surrey Hills,706 Canterbury Rd,2,h,680000.0,PI,Noel,10/12/2016,11.2,3127.0,...,0.0,86.411765,260.0,390.0,444.500000,499.0,1699.0,1699.000000,1699.0,68.0
11675,Lalor,123 Gillwell Rd,4,h,715000.0,S,Barry,3/09/2017,16.3,3075.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4544,Port Melbourne,516/99 Dow St,2,u,820000.0,VB,Cayzer,14/05/2016,3.8,3207.0,...,0.0,200.210117,1150.0,360.0,1480.790698,7000.0,1850.0,4743.964286,17216.0,257.0
4610,Prahran,16 Park Rd,3,t,1245000.0,PI,Marshall,6/08/2016,4.5,3181.0,...,22.0,148.169565,1402.0,250.0,868.148148,2730.0,860.0,3304.382353,9100.0,460.0
1537,Canterbury,33 Myrtle Rd,3,h,1587500.0,S,Marshall,3/12/2016,9.0,3126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10763,Craigieburn,28/60 Cradle Mountain Dr,2,t,310000.0,PI,Ray,15/07/2017,20.6,3064.0,...,12.0,71.404762,251.0,180.0,185.000000,190.0,NaN,NaN,NaN,42.0
7202,Bellfield,125 Oriel Rd,3,h,894000.0,S,Ray,8/04/2017,9.5,3081.0,...,25.0,83.657895,453.0,200.0,291.428571,400.0,600.0,937.500000,1600.0,38.0

A continuación, analizamos la cantidad de datos faltantes en el dataset merged_sales_df.

In [ ]:
merged_sales_df.columns
print(merged_sales_df.isnull().sum()[merged_sales_df.isnull().sum() > 0])
print(round((merged_sales_df.isnull().sum())/merged_sales_df.shape[0],2)[merged_sales_df.isnull().sum() > 0])

Car                            61
BuildingArea                 6122
YearBuilt                    5081
CouncilArea                  1227
zipcode                      1669
airbnb_price_min             1669
airbnb_price_mean            1669
airbnb_price_max             1669
airbnb_weekly_price_min      1731
airbnb_weekly_price_mean     1731
airbnb_weekly_price_max      1731
airbnb_monthly_price_min     1938
airbnb_monthly_price_mean    1938
airbnb_monthly_price_max     1938
zipcode_count                1669
dtype: int64
Car                          0.00
BuildingArea                 0.48
YearBuilt                    0.40
CouncilArea                  0.10
zipcode                      0.13
airbnb_price_min             0.13
airbnb_price_mean            0.13
airbnb_price_max             0.13
airbnb_weekly_price_min      0.14
airbnb_weekly_price_mean     0.14
airbnb_weekly_price_max      0.14
airbnb_monthly_price_min     0.15
airbnb_monthly_price_mean    0.15
airbnb_monthly_price_max     0.15
zipcode_count                0.13
dtype: float64

Observando que los atributos "airbnb_weekly_price" e "airbnb_monthly_price" contienen un 12% y un 14% de datos faltantes respectivamente, se considera necesario eliminar  estos datos del dataframe merged_sales_df para evitar que estos generen complicaciones innecesearias en la etapa de imputación, ya que  se estaría aportando información irrelevante y artificial, lo cual no tiene sentido teniendo en cuenta que estamos realizando una limpieza y curación de los datos. **Es por esto que únicamente nos quedaremos con la columna "airbnb_price_mean", la cual contiene menor cantidad de datos nulos.**

In [ ]:
#Drop columns with missing data
merged_sales_drop_df=merged_sales_df.drop(['airbnb_weekly_price_min', 'airbnb_weekly_price_mean',
                              'airbnb_weekly_price_max','airbnb_monthly_price_min','airbnb_monthly_price_mean',
                              'airbnb_monthly_price_max','airbnb_price_min','airbnb_price_max'], axis=1)

**Investigamos otras variables que podrían servir para combinar los datos.**

Una variable podría ser el barrio, para lo cual determinaríamos (utilizando un algoritmo adecuado) qué latitud y qué longitud corresponde para cada barrio usando el dataset de airbnb. Luego, utilizaríamos esa información para discriminar por barrio el dataset de Melbourne.

Y otra variable más podría ser la distancia de la vivienda a la costa, la cual la determinaríamos también utilizando la latitud y longitud. Esta variable la dividiríamos en intervalos, y pensamos que esta variable podría afectar el precio de la vivienda.

## Ejercicio 3:

Crear y guardar un nuevo conjunto de datos con todas las transformaciones realizadas anteriormente.

In [ ]:
# Read Melb dataframe
melb_df = pandas.read_csv(
    'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/melb_data.csv')
# Read airbnb dataframe
airbnb_df = pandas.read_csv(
    'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/cleansed_listings_dec18.csv')

# Drop rows with outliers using the 3 sigma rule and frequency in categorical variables
categorical_cols = ['Type','CouncilArea']
numerical_cols = ['Rooms',  'Bedroom2', 'Bathroom','Distance',  'Car',
       'Landsize', 'BuildingArea', 'YearBuilt','Price']

cols = numerical_cols + categorical_cols + ["Postcode"]

n_desvios = 3


# Numerical filtering 3 sigma
print("Numerical\n")
idx_to_delete_numerical = filter_outliers_mask(melb_df, numerical_cols, n_desvios_ = n_desvios, verbosity = True)

# Categorical filtering
print("\n Categorical")
idx_to_delete_categorical = filter_categorical(melb_df, categorical_cols, perc_of_cut = 0.001, verbosity = True)

idx_to_delete = numpy.append(idx_to_delete_numerical, idx_to_delete_categorical)
idx_to_delete = numpy.unique(idx_to_delete)

# Melbourne DataFrame
melb_df = filter_df(melb_df, idx_to_delete)
melb_df = melb_df[cols]

airbnb_df['zipcode'] = pandas.to_numeric(airbnb_df.zipcode, errors='coerce')

# Get Zipcode's features from airbnb dataset
relevant_cols = ['zipcode', 'price', 'weekly_price', 'monthly_price']

# Groupby
airbnb_price_by_zipcode = airbnb_df[relevant_cols].groupby('zipcode')\
  .agg({'price': ['min', 'mean', "max"], 'weekly_price': ['min', 'mean', "max"],
        'monthly_price': ['min', 'mean', "max"], "zipcode": "count"})\
  .reset_index()
# Flatten the two level columns
airbnb_price_by_zipcode.columns = [
  ' '.join(col).strip()
  for col in airbnb_price_by_zipcode.columns.values]
# Rename columns
airbnb_price_by_zipcode = airbnb_price_by_zipcode.rename(
    columns={'price min': "airbnb_price_min",
             'price mean': 'airbnb_price_mean',
             'price max':'airbnb_price_max',
             'weekly_price min': 'airbnb_weekly_price_min',
             'weekly_price mean': 'airbnb_weekly_price_mean',
             'weekly_price max': 'airbnb_weekly_price_max',
             'monthly_price min': 'airbnb_monthly_price_min',
             'monthly_price mean': 'airbnb_monthly_price_mean',
             'monthly_price max': 'airbnb_monthly_price_max',
             'zipcode count': 'zipcode_count'
                }
)

# Filter  
n_registros = 25
airbnb_price_by_zipcode_min= airbnb_price_by_zipcode[airbnb_price_by_zipcode["zipcode_count"] >= n_registros] 

# Change type
airbnb_price_by_zipcode_min.loc[:, "zipcode"] = airbnb_price_by_zipcode_min.zipcode.astype(float)
melb_df.loc[:, "Postcode"] = melb_df.Postcode.astype(float)

# Merge
merged_sales_df = melb_df.merge(
    airbnb_price_by_zipcode_min, how='left',
    left_on='Postcode', right_on='zipcode'
)
#Drop columns with missing data
merged_sales_drop_df=merged_sales_df.drop(['airbnb_weekly_price_min', 'airbnb_weekly_price_mean',
                              'airbnb_weekly_price_max','airbnb_monthly_price_min','airbnb_monthly_price_mean',
                              'airbnb_monthly_price_max','airbnb_price_min','airbnb_price_max'], axis=1)

merged_sales_drop_df.to_csv("/content/melb_data_processed.csv", index=False)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (35,77) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

Numerical

Rooms
0.32530595528008216
Bedroom2
0.33139326001719105
Bathroom
0.45084930122347244
Distance
0.5788966792346524
Car
0.5978809976183062
Landsize
7.146407581386584
BuildingArea
3.5600638558653595
YearBuilt
0.018971884592221013
Price
0.5943294471922271
DF Size 13580
Eliminaremos un 7.2% de los registros
DF Processed size:  12602

 Categorical
DF Size 13580
Eliminaremos un 0.1% de los registros
DF Processed size:  13563

In [ ]:
merged_sales_drop_df.columns
merged_sales_drop_df.isnull().sum()[merged_sales_drop_df.isnull().sum() > 0]

Car                    61
BuildingArea         6122
YearBuilt            5081
CouncilArea          1227
zipcode              1669
airbnb_price_mean    1669
zipcode_count        1669
dtype: int64

In [ ]:
melb_df.Postcode.dtype, airbnb_price_by_zipcode_min.zipcode.dtype

(dtype('float64'), dtype('float64'))

In [ ]:
merged_sales_drop_df.to_csv('merged_sales_df.csv')

from google.colab import files
files.download('merged_sales_df.csv')

In [ ]:
merged_sales_drop_df

,Rooms,Bedroom2,Bathroom,Distance,Car,Landsize,BuildingArea,YearBuilt,Price,Type,CouncilArea,Postcode,zipcode,airbnb_price_mean,zipcode_count
0,2,2.0,1.0,2.5,1.0,202.0,NaN,NaN,1480000.0,h,Yarra,3067.0,3067.0,130.624031,258.0
1,2,2.0,1.0,2.5,0.0,156.0,79.0,1900.0,1035000.0,h,Yarra,3067.0,3067.0,130.624031,258.0
2,3,3.0,2.0,2.5,0.0,134.0,150.0,1900.0,1465000.0,h,Yarra,3067.0,3067.0,130.624031,258.0
3,3,3.0,2.0,2.5,1.0,94.0,NaN,NaN,850000.0,h,Yarra,3067.0,3067.0,130.624031,258.0
4,4,3.0,1.0,2.5,2.0,120.0,142.0,2014.0,1600000.0,h,Yarra,3067.0,3067.0,130.624031,258.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12779,3,3.0,2.0,16.5,2.0,256.0,NaN,NaN,582000.0,h,NaN,3049.0,NaN,NaN,NaN
12780,4,4.0,2.0,16.7,2.0,652.0,NaN,1981.0,1245000.0,h,NaN,3150.0,3150.0,124.026455,189.0
12781,3,3.0,2.0,6.8,2.0,333.0,133.0,1995.0,1031000.0,h,NaN,3016.0,3016.0,191.094595,74.0
12782,3,3.0,2.0,6.8,4.0,436.0,NaN,1997.0,1170000.0,h,NaN,3016.0,3016.0,191.094595,74.0
12783,4,4.0,1.0,6.3,1.0,362.0,112.0,1920.0,1285000.0,h,NaN,3013.0,3013.0,135.609756,82.0